import { expect,test,type Page } from "@playwright/test";
const viewports=[{width:1448,height:1086},{width:1366,height:768},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}];
async function setTheme(page:Page,value:"dark"|"light"){await page.addInitScript(v=>localStorage.setItem("organicai-theme",v),value)}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(0)}
async function openAbout(page:Page){await page.goto("/about");await expect(page.getByRole("heading",{level:1,name:/human-centred compass/})).toBeVisible()}

test.describe("spacious About page",()=>{
  test("renders once inside the unified global shell",async({page})=>{await setTheme(page,"dark");await openAbout(page);await expect(page.locator("header.no-print")).toHaveCount(1);await expect(page.getByTestId("global-header")).toHaveCount(1);await expect(page.locator(".organic-gradient-bg > main")).toHaveCount(1);await expect(page.locator(".about-page")).toHaveCount(1);await expect(page.getByRole("navigation",{name:"Global navigation"}).getByRole("link",{name:"About",exact:true})).toHaveAttribute("aria-current","page")});
  test("old compressed mosaic is absent and page scrolls naturally",async({page})=>{await setTheme(page,"dark");await page.setViewportSize({width:1448,height:1086});await openAbout(page);await expect(page.locator(".about-content-mosaic,.about-mosaic-panel")).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollHeight/window.innerHeight)).toBeGreaterThan(4)});
  test("desktop hero uses two columns and substantial height",async({page})=>{await setTheme(page,"dark");await page.setViewportSize({width:1448,height:1086});await openAbout(page);const hero=page.locator(".about-hero");expect((await hero.boundingBox())!.height).toBeGreaterThanOrEqual(540);expect((await hero.locator(".about-hero-copy").boundingBox())!.x).toBeLessThan((await hero.locator(".about-hero-scene").boundingBox())!.x)});
  test("mobile hero stacks copy above a readable scene",async({page})=>{await setTheme(page,"dark");await page.setViewportSize({width:390,height:844});await openAbout(page);const copy=await page.locator(".about-hero-copy").boundingBox();const scene=await page.locator(".about-hero-scene").boundingBox();expect(scene!.y).toBeGreaterThanOrEqual(copy!.y+copy!.height-1);expect(scene!.height).toBeGreaterThanOrEqual(340)});
  test("all required editorial sections are present",async({page})=>{await setTheme(page,"dark");await openAbout(page);for(const name of ["Technology should strengthen human capacity","AI is transforming everything, but people are often left without a compass","From fear to agency","One journey connecting reflection","Technology follows human needs","Designed for people navigating","Your future with AI should be designed","Begin with reflection"]){await expect(page.getByRole("heading",{name:new RegExp(name),exact:false}).first()).toBeVisible()}await expect(page.locator(".about-problem-grid article")).toHaveCount(4);await expect(page.locator(".about-module-grid article")).toHaveCount(4);await expect(page.locator(".about-audience-grid article")).toHaveCount(3)});
  test("primary public actions resolve",async({page})=>{await setTheme(page,"dark");await openAbout(page);const links=[["Start Your Diagnostic","/diagnostic"],["See How It Works","/how-it-works"],["Explore the Research","/research"],["Read the Principles","/principles"]] as const;for(const [name,path] of links)await expect(page.getByRole("link",{name,exact:true}).first()).toHaveAttribute("href",path)});
  test("body typography remains readable",async({page})=>{await setTheme(page,"dark");for(const viewport of [{width:1448,height:1086},{width:390,height:844}]){await page.setViewportSize(viewport);await openAbout(page);const sizes=await page.locator(".about-problem-grid p,.about-module-grid p,.about-audience-grid p").evaluateAll(nodes=>nodes.map(node=>parseFloat(getComputedStyle(node).fontSize)));expect(Math.min(...sizes)).toBeGreaterThanOrEqual(14)}});
  test("dark and light themes remain readable",async({page})=>{await setTheme(page,"dark");await openAbout(page);for(const value of ["dark","light"] as const){await page.evaluate(v=>{localStorage.setItem("organicai-theme",v);document.documentElement.dataset.theme=v},value);await expect(page.locator("html")).toHaveAttribute("data-theme",value);const colors=await page.locator(".about-page").evaluate(node=>({color:getComputedStyle(node).color,background:getComputedStyle(node).backgroundColor}));expect(colors.color).not.toBe(colors.background)}});
  test("required viewports have no horizontal overflow",async({page})=>{await setTheme(page,"dark");for(const viewport of viewports){await page.setViewportSize(viewport);await openAbout(page);await noOverflow(page)}});
  test("captures desktop and mobile QA screenshots in both themes",async({page})=>{await setTheme(page,"dark");await page.setViewportSize({width:1448,height:1086});await openAbout(page);await page.screenshot({path:"qa-about-1448x1086.png"});await page.screenshot({path:"qa-about-full-1448.png",fullPage:true});await page.setViewportSize({width:390,height:844});await openAbout(page);await page.screenshot({path:"qa-about-390x844.png"});await page.screenshot({path:"qa-about-full-390.png",fullPage:true});await page.evaluate(()=>{localStorage.setItem("organicai-theme","light");document.documentElement.dataset.theme="light"});await page.screenshot({path:"qa-about-light-390x844.png"});await page.setViewportSize({width:1448,height:1086});await openAbout(page);await page.evaluate(()=>{localStorage.setItem("organicai-theme","light");document.documentElement.dataset.theme="light"});await page.screenshot({path:"qa-about-light-1448x1086.png"})});
});
