import { expect,test,type Page } from "@playwright/test";

const slugs=["human-centred-ai-guidance-beyond-chatbot","rag-source-visible-coaching","designing-for-agency","voice-privacy-consent","building-dissertation-artifact","human-strengths-ai-assisted-work"];
async function theme(page:Page,value:"dark"|"light"="dark"){await page.addInitScript(v=>localStorage.setItem("organicai-theme",v),value)}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(0)}

test.describe("OrganicAI Journal",()=>{
  test("journal replaces the placeholder and exposes six entries",async({page})=>{await theme(page);await page.goto("/blog");await expect(page.getByRole("heading",{level:1,name:/Ideas, evidence, and reflections/})).toBeVisible();await expect(page.getByText(/COMING SOON/i)).toHaveCount(0);await expect(page.getByRole("link",{name:/Return home/i})).toHaveCount(0);await expect(page.locator("#featured-article")).toBeVisible();await expect(page.locator("[data-article-slug]")).toHaveCount(6);await expect(page.locator("header.no-print")).toHaveCount(1)});
  test("category filters and search update visible articles",async({page})=>{await theme(page);await page.goto("/blog");await page.getByRole("button",{name:"RAG & Knowledge"}).click();await expect(page.locator("[data-article-slug]")).toHaveCount(1);await expect(page.getByText("Showing 1 article",{exact:true})).toBeVisible();await page.getByRole("button",{name:/Clear filters/}).click();const search=page.getByPlaceholder("Search the OrganicAI Journal");await search.fill("privacy");await expect(page.locator("[data-article-slug]")).toHaveCount(1);await search.fill("no matching journal phrase");await expect(page.getByText("No journal entries match this search.")).toBeVisible();await page.getByRole("button",{name:"Show all articles"}).click();await expect(page.locator("[data-article-slug]")).toHaveCount(6)});
  test("featured article and every card route resolve",async({page})=>{await theme(page);await page.goto("/blog");await expect(page.locator("#featured-article").getByRole("link",{name:/Read Article/})).toHaveAttribute("href","/blog/human-centred-ai-guidance-beyond-chatbot");for(const slug of slugs){await page.goto(`/blog/${slug}`);await expect(page.getByRole("heading",{level:1})).toBeVisible();await expect(page.getByText("Journal entry not found")).toHaveCount(0)}});
  test("valid article has contents links, related entries, and back navigation",async({page})=>{await theme(page);await page.setViewportSize({width:1448,height:1086});await page.goto("/blog/rag-source-visible-coaching");await expect(page.getByRole("heading",{level:1})).toHaveText("From retrieval to trust: how RAG supports source-visible coaching");const contents=page.locator(".article-layout > aside").getByRole("navigation",{name:"In this article"});await expect(contents).toBeVisible();const hrefs=await contents.getByRole("link").evaluateAll(links=>links.map(link=>link.getAttribute("href")));for(const href of hrefs)expect(href?.startsWith("#")).toBeTruthy();for(const href of hrefs)await expect(page.locator(href!)).toHaveCount(1);await expect(page.locator(".article-related>div>a")).toHaveCount(3);await expect(page.locator('.article-related a[href="/blog/rag-source-visible-coaching"]')).toHaveCount(0);await page.getByRole("link",{name:/Back to all journal entries/}).click();await expect(page).toHaveURL(/\/blog$/)});
  test("invalid slug shows a safe journal not-found state",async({page})=>{await theme(page);await page.goto("/blog/not-a-real-entry");await expect(page.getByRole("heading",{level:1,name:"Journal entry not found"})).toBeVisible();await expect(page.getByRole("link",{name:"Return to the Journal"})).toHaveAttribute("href","/blog");await expect(page.getByRole("link",{name:"Explore the Research"})).toHaveAttribute("href","/research")});
  test("Journal remains active on article routes",async({page})=>{await theme(page);await page.setViewportSize({width:1448,height:1086});await page.goto("/blog/designing-for-agency");const nav=page.getByRole("navigation",{name:"Global navigation"});await expect(nav.getByRole("link",{name:"Journal",exact:true})).toHaveAttribute("aria-current","page")});
  test("newsletter validates honestly without claiming persistence",async({page})=>{await theme(page);await page.goto("/blog");const newsletter=page.locator(".blog-newsletter");const input=newsletter.getByLabel("Email address");await input.fill("invalid");await newsletter.getByRole("button",{name:"Follow the Journal"}).click();await expect(newsletter.getByRole("status")).toContainText("valid email");await input.fill("reader@example.com");await newsletter.getByRole("button",{name:"Follow the Journal"}).click();await expect(newsletter.getByRole("status")).toHaveText("Thank you. Newsletter delivery is not connected in this research prototype yet.")});
  test("required viewports and themes avoid horizontal overflow",async({page})=>{await theme(page,"dark");for(const viewport of [{width:1448,height:1086},{width:1366,height:768},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto("/blog");await noOverflow(page)}for(const value of ["light","dark"] as const){for(const viewport of [{width:1448,height:1086},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto("/blog/human-centred-ai-guidance-beyond-chatbot");await page.evaluate(v=>{localStorage.setItem("organicai-theme",v);document.documentElement.dataset.theme=v},value);await expect(page.locator("html")).toHaveAttribute("data-theme",value);await noOverflow(page)}}});
  test("captures journal and article QA screenshots",async({page})=>{await page.setViewportSize({width:1448,height:1086});await theme(page,"dark");await page.goto("/blog");await expect(page.getByRole("heading",{level:1,name:/Ideas, evidence, and reflections/})).toBeVisible();await page.screenshot({path:"qa-blog-1448x1086.png"});await page.screenshot({path:"qa-blog-full-1448.png",fullPage:true});await page.goto("/blog/human-centred-ai-guidance-beyond-chatbot");await expect(page.getByRole("heading",{level:1,name:/requires more than a chatbot/})).toBeVisible();await page.screenshot({path:"qa-blog-article-1448x1086.png"});await page.setViewportSize({width:390,height:844});await page.goto("/blog");await expect(page.getByRole("heading",{level:1,name:/Ideas, evidence, and reflections/})).toBeVisible();await page.screenshot({path:"qa-blog-390x844.png"});await page.screenshot({path:"qa-blog-full-390.png",fullPage:true});await page.goto("/blog/human-centred-ai-guidance-beyond-chatbot");await expect(page.getByRole("heading",{level:1,name:/requires more than a chatbot/})).toBeVisible();await page.screenshot({path:"qa-blog-article-390x844.png"});await noOverflow(page)});
});
