import {expect,test,type Page} from "@playwright/test";
const viewports=[{width:1448,height:1086},{width:1366,height:768},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}];
async function theme(page:Page,value:"dark"|"light"="dark"){await page.addInitScript(v=>localStorage.setItem("organicai-theme",v),value)}
async function open(page:Page){await page.goto("/");await expect(page.getByRole("heading",{level:1,name:/Design your future/})).toBeVisible()}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(0)}

test.describe("cinematic OrganicAI homepage",()=>{
 test("renders once in the unified global shell with one h1",async({page})=>{await theme(page);await open(page);await expect(page.locator("h1")).toHaveCount(1);await expect(page.locator("header.no-print")).toHaveCount(1);await expect(page.getByTestId("global-header")).toHaveCount(1);await expect(page.locator(".organic-gradient-bg > main")).toHaveCount(1);await expect(page.getByRole("navigation",{name:"Global navigation"}).getByRole("link",{name:"Home",exact:true})).toHaveAttribute("aria-current","page")});
 test("hero has accessible muted inline video and poster",async({page})=>{await theme(page);await open(page);const video=page.locator(".home-hero video");await expect(video).toHaveCount(1);expect(await video.evaluate((node:HTMLVideoElement)=>node.muted)).toBeTruthy();await expect(video).toHaveAttribute("playsinline","");await expect(video).toHaveAttribute("poster","/images/organicai-hero-human-ai-bg-v2.png");await expect(page.getByRole("button",{name:/overview video/})).toBeVisible()});
 test("primary public actions resolve",async({page})=>{await theme(page);await open(page);for(const [name,path] of [["Start Your Diagnostic","/diagnostic"],["See How It Works","/how-it-works"],["Explore the Research","/research"]])await expect(page.getByRole("link",{name,exact:true}).first()).toHaveAttribute("href",path)});
 test("major narrative, journey, audience, prototype and manifesto sections exist",async({page})=>{await theme(page);await open(page);for(const name of ["Technology should strengthen human capacity","Understand yourself before asking AI","More than an answer","Speak, reflect","Build a path that evolves","From reflection to meaningful action","A system built to support agency","For people navigating change","See how the OrganicAI experience connects","Your future with AI should be designed","Begin with reflection"]){await expect(page.getByRole("heading",{name:new RegExp(name)}).first()).toBeVisible()}await expect(page.locator(".home-story")).toHaveCount(4);await expect(page.locator(".home-audience article")).toHaveCount(3);await expect(page.locator(".home-prototype article")).toHaveCount(4);await expect(page.getByText(/testimonial/i)).toHaveCount(0)});
 test("reduced motion keeps readable poster-only hero",async({page})=>{await page.emulateMedia({reducedMotion:"reduce"});await theme(page);await open(page);await expect(page.locator(".home-hero source")).toHaveCount(0);await expect(page.locator(".home-hero video")).toHaveAttribute("poster",/organicai-hero/);await expect(page.locator(".home-hero-copy")).toBeVisible()});
 test("desktop stories alternate and mobile stories stack",async({page})=>{await theme(page);await page.setViewportSize({width:1448,height:1086});await open(page);const first=page.locator(".home-story").first();expect((await first.locator(".home-story-media").boundingBox())!.x).toBeLessThan((await first.locator(".home-story-copy").boundingBox())!.x);const second=page.locator(".home-story").nth(1);expect((await second.locator(".home-story-copy").boundingBox())!.x).toBeLessThan((await second.locator(".home-story-media").boundingBox())!.x);await page.setViewportSize({width:390,height:844});await open(page);for(const section of await page.locator(".home-story").all()){const media=await section.locator(".home-story-media").boundingBox(),copy=await section.locator(".home-story-copy").boundingBox();expect(copy!.y).toBeGreaterThan(media!.y)}});
 test("required viewports avoid overflow and page scrolls naturally",async({page})=>{await theme(page);for(const viewport of viewports){await page.setViewportSize(viewport);await open(page);await noOverflow(page)}expect(await page.evaluate(()=>document.documentElement.scrollHeight/window.innerHeight)).toBeGreaterThan(5)});
 test("light and dark themes remain readable",async({page})=>{await theme(page);await open(page);for(const value of ["dark","light"] as const){await page.evaluate(v=>{localStorage.setItem("organicai-theme",v);document.documentElement.dataset.theme=v},value);await expect(page.locator("html")).toHaveAttribute("data-theme",value);const colors=await page.locator(".home-mission").evaluate(node=>({text:getComputedStyle(node).color,bg:getComputedStyle(node).backgroundColor}));expect(colors.text).not.toBe(colors.bg)}});
 test("captures all requested QA screenshots",async({page})=>{await theme(page);await page.setViewportSize({width:1448,height:1086});await open(page);await page.screenshot({path:"qa-home-1448x1086.png"});await page.screenshot({path:"qa-home-full-1448.png",fullPage:true});await page.setViewportSize({width:390,height:844});await open(page);await page.screenshot({path:"qa-home-390x844.png"});await page.screenshot({path:"qa-home-full-390.png",fullPage:true});await page.evaluate(()=>{localStorage.setItem("organicai-theme","light");document.documentElement.dataset.theme="light"});await page.screenshot({path:"qa-home-light-390x844.png"});await page.setViewportSize({width:1448,height:1086});await open(page);await page.evaluate(()=>{localStorage.setItem("organicai-theme","light");document.documentElement.dataset.theme="light"});await page.screenshot({path:"qa-home-light-1448x1086.png"});await page.emulateMedia({reducedMotion:"reduce"});await page.goto("/");await expect(page.locator(".home-hero-copy")).toBeVisible();await page.screenshot({path:"qa-home-reduced-motion.png"})});
});
