import {expect,test,type Page} from "@playwright/test";
import {installMockAuthSession} from "./utils/authSession";
const source={source_id:"source-1",id:"source-1",document_name:"responsible_ai",section_title:"Human oversight",excerpt:"Human judgment and transparent sources remain central.",chunk_text:"Human judgment and transparent sources remain central.",similarity_score:.82,score:.82,rank:1,relevance_status:"high"};
async function mocks(page:Page,{insufficient=false}={}){await installMockAuthSession(page,{state:"demo"});await page.route("**/api/rag/ask",route=>route.fulfill({json:{query:"responsible AI",answer:insufficient?"I do not have sufficient information in the current OrganicAI Knowledge Base to answer this reliably.":"Grounded guidance keeps human judgment central.",rag_run_id:"run-1",sources:insufficient?[]:[source],sources_used:insufficient?[]:[source],has_sources:!insufficient,confidence_note:insufficient?"No source met the configured relevance and safety requirements.":"Grounded in retrieved sources.",ethical_note:"Verify high-impact decisions.",insufficient_context:insufficient,context_quality:insufficient?"insufficient":"strong",fallback_reason:insufficient?"no_source_above_threshold":null,retrieval_summary:{retrieved_count:1,used_count:insufficient?0:1,highest_score:.82,threshold:.1,retrieval_duration_ms:4},suggested_actions:["Browse Knowledge Base"]}}));await page.route("**/api/rag/runs/**/feedback",route=>route.fulfill({json:{id:"feedback-1",rag_run_id:"run-1",rating:"helpful",saved:true}}));await page.route("**/api/rag/runs/**/sources/**/feedback",route=>route.fulfill({json:{id:"feedback-2",rag_run_id:"run-1",source_id:"source-1",rating:"relevant",saved:true}}));await page.route("**/api/rag/search**",route=>route.fulfill({json:{query:"AI",results:[{id:"chunk-1",document_name:"responsible_ai",section_title:"Agency",chunk_text:"Human oversight remains important.",score:.73}]}}))}
async function ask(page:Page){await page.goto("/knowledge-base");const box=page.getByPlaceholder("What would you like to understand?");await box.fill("What does responsible AI mean?");const button=page.getByRole("button",{name:"Ask Knowledge Base"});await button.focus();await page.keyboard.press("Enter")}
test.describe("RAG feedback and observability UI",()=>{
 test("Knowledge Base Ask displays answer, quality and source",async({page})=>{await mocks(page);await ask(page);await expect(page.getByText("Grounded guidance keeps human judgment central.")).toBeVisible();await expect(page.getByText("Context quality: strong")).toBeVisible();await expect(page.getByText("Retrieval similarity: 0.820")).toBeVisible()});
 test("answer feedback saves and partial reveals reason choices",async({page})=>{await mocks(page);await ask(page);const control=page.locator(".kb-answer .rag-feedback");await control.getByRole("button",{name:"Partially",exact:true}).click();await expect(page.getByLabel("What was missing?")).toBeVisible();await expect(control.getByRole("status")).toHaveText("Feedback saved for research evaluation.")});
 test("source feedback saves independently",async({page})=>{await mocks(page);await ask(page);const control=page.locator(".kb-results .rag-feedback");await control.getByRole("button",{name:"Relevant",exact:true}).click();await expect(control.getByRole("status")).toContainText("Feedback saved")});
 test("insufficient result has explicit fallback and retry",async({page})=>{await mocks(page,{insufficient:true});await ask(page);await expect(page.getByText("Insufficient Knowledge Base context")).toBeVisible();await expect(page.getByText(/do not have sufficient information/)).toBeVisible();await page.getByRole("button",{name:"Try another question"}).click();await expect(page.getByPlaceholder("What would you like to understand?")).toHaveValue("")});
 test("existing Knowledge Base search remains functional",async({page})=>{await mocks(page);await page.goto("/knowledge-base");const input=page.getByPlaceholder(/Search responsible AI/);await input.fill("AI literacy");await page.locator(".kb-search").getByRole("button",{name:"Search"}).click();await expect(page.getByText("Retrieval similarity: 0.730")).toBeVisible()});
 test("feedback controls support keyboard and aria-pressed",async({page})=>{await mocks(page);await ask(page);const helpful=page.getByRole("button",{name:"Helpful",exact:true});await helpful.focus();await page.keyboard.press("Enter");await expect(helpful).toHaveAttribute("aria-pressed","true")});
 test("light, dark and mobile remain readable without overflow",async({page})=>{await mocks(page);await page.addInitScript(()=>localStorage.setItem("organicai-theme","dark"));for(const value of ["dark","light"]){await page.setViewportSize({width:390,height:844});await ask(page);await page.evaluate(v=>{localStorage.setItem("organicai-theme",v);document.documentElement.dataset.theme=v},value);expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(0);await expect(page.locator("html")).toHaveAttribute("data-theme",value)}});
 test("Coach grounded answer exposes feedback controls",async({page})=>{await installMockAuthSession(page,{state:"demo"});await page.route("**/api/chat",route=>route.fulfill({json:{answer:"Grounded coach answer.",conversation_id:"conversation-1",message_id:"message-1",sources_used:[source],confidence_note:"Grounded in sources.",ethical_note:"Keep human judgment.",grounding_status:"grounded",retrieval_status:{rag_run_id:"run-1",context_quality:"strong"},timing:{}}}));await page.route("**/api/rag/runs/**/feedback",route=>route.fulfill({json:{saved:true}}));await page.goto("/coach/demo-profile");const input=page.getByPlaceholder("Ask anything");await input.fill("How should I use AI responsibly?");await page.getByRole("button",{name:"Send message"}).click();await expect(page.getByText("Grounded coach answer.")).toBeVisible();await expect(page.getByText("Was this response useful?")).toBeVisible()});
});
