import { createContext, type ReactNode, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import { sendCoachMessage } from "../api/chatApi";
import { synthesizeSpeech, transcribeAudio } from "../api/voiceApi";
import type { ChatMessage } from "../types/chat";
import { useAppActions } from "../hooks/useAppActions";
import { getProfileFeedback, updateProfileFeedback } from "../api/profileApi";
import { generateRoadmap } from "../api/roadmapApi";

export type CoachState="idle"|"listening"|"transcribing"|"classifying"|"retrieving"|"thinking"|"speaking"|"executing"|"error";
export type CoachPreferences={isMuted:boolean;autoPlay:boolean;autoSendTranscript:boolean;storeTranscripts:boolean;storeAudio:boolean;voicePersonality:string;conversationMode:string;language:"en"|"ro"|"no";voiceConsent:boolean};
type CoachValue={state:CoachState;messages:ChatMessage[];conversationId:string|null;transcript:string;interimTranscript:string;audioUrl:string;preferences:CoachPreferences;selectedProfileNode:string|null;selectedRecommendationId:string|null;currentSources:NonNullable<ChatMessage["sourcesUsed"]>;currentConfidenceNote:string;currentEthicalNote:string;lastRecognizedCommand:string;error:string;recordingSeconds:number;setTranscript:(value:string)=>void;setSelectedProfileNode:(value:string|null)=>void;setSelectedRecommendationId:(value:string|null)=>void;setPreferences:(next:Partial<CoachPreferences>)=>void;sendTextMessage:(text:string,mode?:"text"|"voice")=>Promise<void>;startListening:()=>Promise<void>;stopListening:()=>void;cancelTranscript:()=>void;stopSpeaking:()=>void;replayLastAnswer:()=>Promise<void>;executeCommand:(command:string)=>Promise<void>;clearConversation:()=>void};
export const CoachContext=createContext<CoachValue|undefined>(undefined);
const PREF_KEY="organicai_coach_preferences",HISTORY_KEY="organicai_coach_temp_history";
const initialPreferences:CoachPreferences={isMuted:false,autoPlay:false,autoSendTranscript:false,storeTranscripts:true,storeAudio:false,voicePersonality:"Calm Guide",conversationMode:"Explain simply",language:"en",voiceConsent:false};
const welcome:ChatMessage={id:"welcome",role:"assistant",content:"Hi, I’m OrganicAI Coach. You can use text or voice, and every answer remains available as captions.",createdAt:new Date().toISOString(),groundingStatus:"general"};
const make=(role:"user"|"assistant",content:string,mode:"text"|"voice"="text"):ChatMessage=>({id:`${role}-${Date.now()}-${Math.random()}`,role,content,createdAt:new Date().toISOString(),inputMode:mode});

export function CoachProvider({children}:{children:ReactNode}){
  const actions=useAppActions();const location=useLocation();const [state,setState]=useState<CoachState>("idle");const [messages,setMessages]=useState<ChatMessage[]>(()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"null")||[welcome]}catch{return[welcome]}});const [conversationId,setConversationId]=useState<string|null>(null);const [transcript,setTranscript]=useState("");const [interimTranscript]=useState("");const [audioUrl,setAudioUrl]=useState("");const [selectedProfileNode,setSelectedProfileNode]=useState<string|null>(null);const [selectedRecommendationId,setSelectedRecommendationId]=useState<string|null>(null);const [preferences,setPreferencesState]=useState<CoachPreferences>(()=>{try{return{...initialPreferences,...JSON.parse(localStorage.getItem(PREF_KEY)||"{}")}}catch{return initialPreferences}});const [lastRecognizedCommand,setLastRecognizedCommand]=useState("");const [error,setError]=useState("");const [recordingSeconds,setRecordingSeconds]=useState(0);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<BlobPart[]>([]);const stream=useRef<MediaStream|null>(null);const audio=useRef<HTMLAudioElement|null>(null);
  useEffect(()=>localStorage.setItem(PREF_KEY,JSON.stringify(preferences)),[preferences]);useEffect(()=>{if(preferences.storeTranscripts)localStorage.setItem(HISTORY_KEY,JSON.stringify(messages));else localStorage.removeItem(HISTORY_KEY)},[messages,preferences.storeTranscripts]);useEffect(()=>{if(state!=="listening")return;const timer=window.setInterval(()=>setRecordingSeconds(v=>v+1),1000);return()=>clearInterval(timer)},[state]);
  const stopSpeaking=useCallback(()=>{audio.current?.pause();if(audio.current)audio.current.currentTime=0;setState("idle")},[]);useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.key==="Escape")stopSpeaking()};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener)},[stopSpeaking]);useEffect(()=>()=>{stream.current?.getTracks().forEach(track=>track.stop());audio.current?.pause()},[]);
  const setPreferences=(next:Partial<CoachPreferences>)=>setPreferencesState(current=>({...current,...next}));
  async function play(text:string){if(preferences.isMuted)return;try{const result=await synthesizeSpeech(text);if(!result.audioUrl)throw new Error();setAudioUrl(result.audioUrl);const player=new Audio(result.audioUrl);audio.current=player;player.onended=()=>setState("idle");setState("speaking");await player.play()}catch{setError("Voice playback is unavailable. Your text answer is still ready.");setState("idle")}}
  async function executeCommand(raw:string){setState("executing");const result=actions.executeVoiceCommand(raw);if(result.recognized){const confirmation=`Voice command recognized: ${result.label}. ${result.message||""}`;setLastRecognizedCommand(result.label||raw);setMessages(current=>[...current,make("assistant",confirmation)]);if(preferences.autoPlay&&!preferences.isMuted)await play(result.message||confirmation);else setState("idle")}else{setState("idle")}}
  async function sendTextMessage(text:string,mode:"text"|"voice"="text"){
    if(!text.trim())return;const normalized=text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z\s]/g,"").trim();if(["stop speaking","stop voice","opreste vocea","taci"].includes(normalized)){setMessages(current=>[...current,make("user",text,mode),make("assistant","Voice command recognized: Stop Speaking.")]);setLastRecognizedCommand("Stop Speaking");stopSpeaking();return}if(["repeat answer","repeat that","repeta raspunsul"].includes(normalized)){setLastRecognizedCommand("Repeat Answer");await replayLastAnswer();return}setError("");const localCommand=actions.executeVoiceCommand(text);if(localCommand.recognized){setMessages(current=>[...current,make("user",text,mode)]);await executeCommand(text);setTranscript("");return}setMessages(current=>[...current,make("user",text,mode)]);setTranscript("");setState("classifying");const retrievalTimer=window.setTimeout(()=>setState("retrieving"),180);
    try{const response=await sendCoachMessage({message:text,profileId:actions.activeProfileId,conversationId,mode,voicePersonality:preferences.voicePersonality,conversationMode:preferences.conversationMode,route:location.pathname,selectedProfileNode,language:preferences.language,clientContext:{theme:document.documentElement.dataset.theme}});clearTimeout(retrievalTimer);let answer=response.answer;if(response.executedCommand){setLastRecognizedCommand(response.executedCommand.name);setState("executing");const name=response.executedCommand.name;if(name==="confirm_selected_node"&&selectedProfileNode){const saved=await getProfileFeedback(actions.activeProfileId);await updateProfileFeedback(actions.activeProfileId,{...saved,confirmed_nodes:[...new Set([...saved.confirmed_nodes,selectedProfileNode])]});answer=`Confirmed the ${selectedProfileNode} interpretation. You remain in control of this profile.`}else if(name==="add_note_to_selected_node"&&selectedProfileNode){const saved=await getProfileFeedback(actions.activeProfileId);const note=String(response.executedCommand.parameters.note||"");await updateProfileFeedback(actions.activeProfileId,{...saved,user_notes:{...saved.user_notes,[selectedProfileNode]:note}});answer=`I added that note to ${selectedProfileNode}.`}else if(name==="open_selected_learning_path")actions.executeVoiceCommand("open learning paths");else if(name==="regenerate_roadmap"){await generateRoadmap(actions.activeProfileId);answer="Your roadmap was regenerated using your current profile."}}else setState("thinking");const assistant={...make("assistant",answer),sourcesUsed:response.sourcesUsed,confidenceNote:response.confidenceNote,ethicalNote:response.ethicalNote,intent:response.intent,profileSignals:response.profileSignals,groundingStatus:response.groundingStatus,retrievalStatus:response.retrievalStatus,timing:response.timing};setConversationId(response.conversationId||conversationId);setMessages(current=>[...current,assistant]);if(preferences.autoPlay&&!preferences.isMuted)await play(answer);else setState("idle")}catch{clearTimeout(retrievalTimer);setError("The AI Coach request failed. Check your connection and try again.");setState("error")}
  }
  async function startListening(){if(!preferences.voiceConsent){setError("Voice consent is required before recording.");return}if(!navigator.mediaDevices?.getUserMedia){setError("No microphone is available. You can still use text chat.");return}try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;chunks.current=[];const instance=new MediaRecorder(media,MediaRecorder.isTypeSupported("audio/webm")?{mimeType:"audio/webm"}:undefined);recorder.current=instance;instance.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};instance.onstop=async()=>{media.getTracks().forEach(track=>track.stop());setState("transcribing");try{const result=await transcribeAudio(new Blob(chunks.current,{type:instance.mimeType||"audio/webm"}));setTranscript(result.transcript);setState("idle");if(preferences.autoSendTranscript&&result.transcript.trim())await sendTextMessage(result.transcript,"voice")}catch{setError("We couldn’t transcribe that recording. You can try again or type your message.");setState("error")}};setRecordingSeconds(0);instance.start();setState("listening")}catch{setError("Microphone permission was denied. You can continue with text.");setState("error")}}
  function stopListening(){if(recorder.current?.state==="recording")recorder.current.stop()}
  async function replayLastAnswer(){const latest=[...messages].reverse().find(item=>item.role==="assistant");if(latest)await play(latest.content)}
  function clearConversation(){stopSpeaking();setMessages([welcome]);setConversationId(null);setTranscript("");setError("");localStorage.removeItem(HISTORY_KEY)}
  const latest=[...messages].reverse().find(item=>item.role==="assistant");const value=useMemo<CoachValue>(()=>({state,messages,conversationId,transcript,interimTranscript,audioUrl,preferences,selectedProfileNode,selectedRecommendationId,currentSources:latest?.sourcesUsed||[],currentConfidenceNote:latest?.confidenceNote||"",currentEthicalNote:latest?.ethicalNote||"",lastRecognizedCommand,error,recordingSeconds,setTranscript,setSelectedProfileNode,setSelectedRecommendationId,setPreferences,sendTextMessage,startListening,stopListening,cancelTranscript:()=>setTranscript(""),stopSpeaking,replayLastAnswer,executeCommand,clearConversation}),[state,messages,conversationId,transcript,interimTranscript,audioUrl,preferences,selectedProfileNode,selectedRecommendationId,latest,lastRecognizedCommand,error,recordingSeconds,stopSpeaking,actions.activeProfileId,location.pathname]);return <CoachContext.Provider value={value}>{children}</CoachContext.Provider>
}
