import { apiClient } from "./client";
import type { RecalibrationProposal, Roadmap, RoadmapAction, RoadmapCheckIn } from "../types/roadmap";
export async function generateRoadmap(profileId:string){return (await apiClient.post<Roadmap>("/roadmap/generate",{profile_id:profileId})).data}
export async function getRoadmap(profileId:string){return (await apiClient.get<Roadmap|null>(`/roadmap/${profileId}`)).data}
export async function getRoadmapById(id:string){return (await apiClient.get<Roadmap>(`/roadmaps/${id}`)).data}
export async function updateRoadmap(id:string,patch:Record<string,unknown>){return (await apiClient.patch<Roadmap>(`/roadmaps/${id}`,patch)).data}
export async function getRoadmapActions(id:string){return (await apiClient.get<RoadmapAction[]>(`/roadmaps/${id}/actions`)).data}
export async function createRoadmapAction(id:string,payload:Partial<RoadmapAction>){return (await apiClient.post<RoadmapAction>(`/roadmaps/${id}/actions`,payload)).data}
export async function updateRoadmapAction(id:string,patch:Partial<RoadmapAction>){return (await apiClient.patch<RoadmapAction>(`/roadmap-actions/${id}`,patch)).data}
export async function startRoadmapAction(id:string){return (await apiClient.post<RoadmapAction>(`/roadmap-actions/${id}/start`)).data}
export async function completeRoadmapAction(id:string,outcome=""){return (await apiClient.post<RoadmapAction>(`/roadmap-actions/${id}/complete`,{outcome})).data}
export async function skipRoadmapAction(id:string,reason:string){return (await apiClient.post<RoadmapAction>(`/roadmap-actions/${id}/skip`,{reason})).data}
export async function postponeRoadmapAction(id:string,date?:string,reason="",horizon?:string){return (await apiClient.post<RoadmapAction>(`/roadmap-actions/${id}/postpone`,{date,reason,horizon})).data}
export async function deleteRoadmapAction(id:string){return (await apiClient.delete(`/roadmap-actions/${id}`)).data}
export async function submitRoadmapCheckIn(id:string,payload:Record<string,unknown>){return (await apiClient.post<RoadmapCheckIn>(`/roadmaps/${id}/check-ins`,payload)).data}
export async function getRoadmapCheckIns(id:string){return (await apiClient.get<RoadmapCheckIn[]>(`/roadmaps/${id}/check-ins`)).data}
export async function proposeRecalibration(id:string){return (await apiClient.post<RecalibrationProposal>(`/roadmaps/${id}/recalibrate`)).data}
export async function applyRecalibration(id:string,selected_changes?:number[]){return (await apiClient.post<Roadmap>(`/roadmaps/${id}/apply-recalibration`,{selected_changes})).data}
export async function getRoadmapVersions(id:string){return (await apiClient.get<Array<{version_number:number;reason:string;created_at:string}>>(`/roadmaps/${id}/versions`)).data}
