from sqlalchemy import delete, select
from sqlalchemy.orm import Session
from app.auth.security import hash_password
from app.config import get_settings
from app.models.conversation import Conversation
from app.models.diagnostic import Diagnostic
from app.models.fear_transform import FearTransformRecord
from app.models.message import Message
from app.models.profile import Profile
from app.models.roadmap import Roadmap
from app.models.roadmap_adaptation import RoadmapAction, RoadmapCheckIn, RoadmapEvent, RoadmapMilestone, RoadmapVersion
from app.models.user import User

DEMO_PROFILE_ID="demo-profile-alex"
DEMO_DIAGNOSTIC_ID="demo-diagnostic-alex"

def is_demo_user(user: User | None) -> bool: return bool(user and user.is_demo)

def diagnostic_payload(): return {"interests":["human-centred artificial intelligence","interior and digital design","creative technology","education","ethical innovation","future of work"],"natural_activities":["visualizing complex ideas","designing meaningful experiences","connecting people and technology","learning new digital tools","building interdisciplinary concepts"],"problems_noticed":["fear and confusion about AI","fragmented learning resources","lack of personalized guidance","difficulty translating AI knowledge into practical action"],"preferred_orientation":["creative","strategic","human-centred","interdisciplinary"],"fears":["professional displacement","loss of human creativity","overdependence on automated systems","misuse of personal data","unequal access to AI opportunities"],"ai_threat_or_opportunity":"AI can become a major opportunity when it augments human creativity and remains transparent, responsible, and user-controlled.","values":["creativity","human dignity","responsibility","learning","contribution","collaboration","autonomy"],"contribution_if_supported":"Create understandable, ethical, and visually engaging AI systems that help people adapt and grow.","skills":["design thinking","visual communication","spatial thinking","software development","research","systems thinking","empathy","concept development"],"preferred_learning_style":["visual","project-based","conversational","practical experimentation"],"cognitive_style":["systems-oriented","reflective","creative","strategic"],"ai_experience":"Intermediate","ai_help_goals":["develop meaningful AI products","improve technical confidence","create a structured learning roadmap","combine design and software engineering","prepare for future work"],"preferred_interaction":"both"}

def profile_payload(): return {"primary_archetype":{"name":"The Visionary Architect","summary":"You combine visual imagination, systems thinking, empathy, and practical execution. Your strongest potential lies in translating complex technologies into understandable, meaningful, and human-centred experiences.","confidence":.92,"signals":["visual systems","future-oriented thinking","responsible innovation"]},"secondary_archetype":{"name":"The Human-Centred Systems Builder","summary":"You connect people, systems, and practical experimentation.","confidence":.86,"signals":["empathy","systems thinking"]},"strengths":[{"name":"Strategic Thinking","score":94,"explanation":"Connects future possibilities with practical priorities.","evidence":[]},{"name":"Creative Problem Solving","score":91,"explanation":"Generates meaningful alternatives.","evidence":[]},{"name":"Empathy and Influence","score":88,"explanation":"Keeps people visible in technical change.","evidence":[]},{"name":"Systems Thinking","score":84,"explanation":"Sees relationships across a complex product.","evidence":[]},{"name":"Adaptability","score":82,"explanation":"Learns through change and experimentation.","evidence":[]}],"values":[{"name":name,"score":90-i*2,"evidence":[]} for i,name in enumerate(["Human Dignity","Creativity","Responsible Innovation","Learning","Autonomy","Meaningful Contribution"])],"fears":diagnostic_payload()["fears"],"creative_tendencies":["conceptual synthesis","visual storytelling","organic and systems-based design","interdisciplinary experimentation","future-oriented thinking"],"ai_collaboration_style":{"name":"Co-Creator","summary":"You work best with AI as an iterative creative and analytical partner. You prefer to generate alternatives, refine ideas, evaluate implications, and keep final judgment under human control.","strengths":["ideation","evaluation"],"cautions":["Keep final judgment human-led"],"recommended_uses":["Generate and compare alternatives"],"human_led_decisions":["authorship","values","final selection"]},"contribution_domains":[{"name":name,"score":score,"explanation":"A high-potential domain for meaningful contribution."} for name,score in [("Future of Work",95),("Human–AI Collaboration",92),("Education and Learning",88),("Sustainable Innovation",84)]],"recommended_learning_paths":[{"name":name,"level":level,"duration":duration,"reason":"Build practical, responsible capability."} for name,level,duration in [("AI Collaboration Mastery","Intermediate","6 weeks"),("Designing the Future","Advanced","8 weeks"),("Leadership in the Age of AI","Intermediate","5 weeks")]],"uncertainties":[],"risk_notes":["Avoid trying to master too many fields simultaneously.","Validate ambitious ideas through small prototypes.","Maintain boundaries between AI assistance and human judgment.","Review privacy implications before using personal or voice data."],"ethical_note":"This is an exploratory profile. You can confirm, correct, or expand it."}

def roadmap_payload(): return {"title":"My Personal Roadmap","summary":"A practical, human-centred direction for Alex Demo.","version":1,"status":"active","contribution_direction":"Build and evaluate a human-centred AI guidance platform combining voice interaction, RAG, personalization, and adaptive roadmaps.","recommended_skills":["RAG architecture","AI evaluation","accessibility","responsible AI","conversational interface design","React and FastAPI architecture","user research","product strategy"],"project_idea":"Build and evaluate a human-centred AI guidance platform combining voice interaction, RAG, personalization, and adaptive roadmaps.","social_contribution_idea":"Provide understandable AI-literacy guidance for professionals and adults adapting to technological change.","ethical_cautions":["Clearly label AI-generated recommendations.","Preserve user choice.","Protect voice and diagnostic data.","Communicate uncertainty."],"recalibration_notes":[],"growth_score":78,"harmony_score":92,"potential_intelligence_score":89,"alignment":92,"growth_momentum":24,"current_streak":28,"focus":"Deep Work","energy":"High"}

def restore_demo(db: Session) -> tuple[User,Profile,Roadmap]:
    s=get_settings(); user=db.scalar(select(User).where(User.email==s.demo_email.lower()))
    if not user: user=User(name="Alex Demo",email=s.demo_email.lower(),hashed_password=hash_password(s.demo_password),is_demo=True);db.add(user);db.flush()
    else: user.name="Alex Demo";user.is_demo=True;user.hashed_password=hash_password(s.demo_password)
    profile_ids=[p.id for p in db.scalars(select(Profile).where(Profile.user_id==user.id)).all()]
    roadmap_ids=[r.id for r in db.scalars(select(Roadmap).where(Roadmap.user_id==user.id)).all()]
    if roadmap_ids:
      for model,column in [(RoadmapAction,RoadmapAction.roadmap_id),(RoadmapCheckIn,RoadmapCheckIn.roadmap_id),(RoadmapEvent,RoadmapEvent.roadmap_id),(RoadmapMilestone,RoadmapMilestone.roadmap_id),(RoadmapVersion,RoadmapVersion.roadmap_id)]: db.execute(delete(model).where(column.in_(roadmap_ids)))
      db.execute(delete(Roadmap).where(Roadmap.id.in_(roadmap_ids)))
    if profile_ids: db.execute(delete(FearTransformRecord).where(FearTransformRecord.profile_id.in_(profile_ids)));db.execute(delete(Profile).where(Profile.id.in_(profile_ids)))
    db.execute(delete(Diagnostic).where(Diagnostic.user_id==user.id)); db.execute(delete(Conversation).where(Conversation.user_id==user.id)); db.flush()
    diagnostic=Diagnostic(id=DEMO_DIAGNOSTIC_ID,user_id=user.id,payload=diagnostic_payload());db.add(diagnostic)
    profile=Profile(id=DEMO_PROFILE_ID,user_id=user.id,diagnostic_id=diagnostic.id,data=profile_payload());db.add(profile)
    roadmap=Roadmap(user_id=user.id,profile_id=profile.id,data=roadmap_payload());db.add(roadmap);db.flush()
    actions=[("seven_days","Morning Alignment","completed"),("seven_days","AI Literacy Session","completed"),("seven_days","Move Your Body","completed"),("seven_days","Deep Work Block","in_progress"),("seven_days","Human–AI Reflection","not_started"),("seven_days","Prototype and Share","not_started"),("thirty_days","Build a Valuable Skill","in_progress"),("thirty_days","Ship a Meaningful Project","in_progress"),("thirty_days","Strengthen Relationships","not_started"),("thirty_days","Optimize Systems","not_started"),("six_months","Complete the dissertation platform","not_started"),("six_months","Evaluate usability and recommendation relevance","not_started"),("six_months","Build a professional OrganicAI case study","not_started"),("six_months","Publish a portfolio-ready demonstration","not_started"),("six_months","Develop a responsible AI service proposition","not_started"),("six_months","Expand professional opportunities in AI and design","not_started")]
    for priority,(horizon,title,status) in enumerate(actions,1): db.add(RoadmapAction(roadmap_id=roadmap.id,profile_id=profile.id,user_id=user.id,horizon=horizon,title=title,description="A realistic demo action supporting Alex’s human-centred AI direction.",first_step="Choose the smallest useful next step.",success_criteria="Record a short outcome.",estimated_minutes=45,priority=priority,status=status,progress_percentage=100 if status=="completed" else 35 if status=="in_progress" else 0,source_type="demo_seed"))
    db.add(RoadmapCheckIn(roadmap_id=roadmap.id,user_id=user.id,profile_id=profile.id,energy_level=4,confidence_level=4,perceived_progress=4,what_worked="A focused deep-work block and a practical AI learning session.",main_blocker="Protecting enough time for ambitious interdisciplinary work."))
    fears=[("AI may make my professional experience irrelevant.","Your previous experience can become the context that makes AI output more useful, realistic, and human-centred."),("Using AI may weaken my own creativity.","Use AI as a divergent-thinking partner while keeping authorship, selection, and meaning under human control.")]
    for fear,reframe in fears: db.add(FearTransformRecord(profile_id=profile.id,input_fear=fear,output={"clarity":"AI changes tasks faster than it removes the need for judgment, context, empathy, and domain expertise.","controllable_factors":["learning practical AI collaboration","building demonstrable projects"],"creative_reframe":reframe,"fifteen_minute_action":"Write down three professional strengths that AI does not possess independently.","seven_day_action":"Build one small AI-assisted project.","ethical_note":"This is exploratory guidance, not a prediction."}))
    conversation=Conversation(user_id=user.id,profile_id=profile.id,title="Demo AI Coach conversations");db.add(conversation);db.flush()
    for role,content in [("user","How can I build trust when introducing AI in my team?"),("assistant","Building trust starts with transparency, education, and early participation. Explain what the system can and cannot do, invite the team to test it, and preserve human review for meaningful decisions. Sources: Responsible AI, AI Literacy, Human–AI Collaboration, Privacy and Voice Data."),("user","What should I focus on this week?"),("assistant","Focus on one deep-work block, one practical AI-learning activity, and one small prototype that you can show to another person."),("user","Can AI replace human creativity?"),("assistant","AI can generate and recombine patterns, but humans still provide intent, lived context, values, selection, responsibility, and meaning.")]: db.add(Message(conversation_id=conversation.id,role=role,content=content,input_mode="text"))
    db.commit();db.refresh(user);db.refresh(profile);db.refresh(roadmap);return user,profile,roadmap

def ensure_demo(db:Session, reset:bool=False):
    s=get_settings(); user=db.scalar(select(User).where(User.email==s.demo_email.lower()))
    if reset or not user or not user.is_demo: return restore_demo(db)
    profile=db.scalar(select(Profile).where(Profile.user_id==user.id).order_by(Profile.created_at.desc()))
    roadmap=db.scalar(select(Roadmap).where(Roadmap.user_id==user.id).order_by(Roadmap.created_at.desc()))
    fear_count=len(db.scalars(select(FearTransformRecord).where(FearTransformRecord.profile_id==profile.id)).all()) if profile else 0
    conversation_count=len(db.scalars(select(Conversation).where(Conversation.user_id==user.id)).all())
    return (user,profile,roadmap) if profile and roadmap and fear_count >= 2 and conversation_count else restore_demo(db)
