export type RoadmapHorizon = "seven_days" | "thirty_days" | "six_months";
export type RoadmapActionStatus = "not_started" | "in_progress" | "completed" | "skipped" | "postponed" | "blocked" | "archived";
export interface RoadmapAction { id:string; roadmap_id:string; profile_id?:string; user_id?:string|null; recommendation_id?:string|null; career_experiment_session_id?:string|null; career_hypothesis_id?:string|null; evidence_gap_id?:string|null; horizon:RoadmapHorizon; title:string; description:string; reason:string; first_step:string; success_criteria:string; estimated_minutes?:number|null; effort:string; impact:string; priority:number; status:RoadmapActionStatus; progress_percentage:number; due_date?:string|null; scheduled_date?:string|null; completed_at?:string|null; skipped_at?:string|null; skip_reason?:string|null; user_notes:string; source_type:string; profile_signals:string[]; rag_sources:unknown[]; ethical_cautions:string[]; created_at:string; updated_at:string; }
export interface RoadmapItem { title:string; description:string; recommendation_id?:string; source?:string; }
export interface RoadmapProgress { total_actions:number; completed_actions:number; in_progress_actions:number; skipped_actions:number; blocked_actions:number; completion_percentage:number; }
export interface RoadmapMilestone { id:string; title:string; description:string; target_date?:string|null; status:string; success_criteria:string; evidence_note:string; linked_action_ids:string[]; completed_at?:string|null; }
export interface RoadmapCheckIn { id:string; roadmap_id:string; check_in_type:string; energy_level?:number|null; confidence_level?:number|null; perceived_progress?:number|null; main_blocker:string; what_worked:string; what_changed:string; user_note:string; created_at:string; }
export interface RoadmapEvent { id:string; roadmap_id:string; action_id?:string|null; user_id?:string|null; event_type:string; metadata?:Record<string, unknown>; created_at:string; }
export interface Roadmap { id:string; profile_id?:string; title:string; summary:string; status:string; version:number; created_at:string; updated_at:string; last_recalibrated_at?:string|null; progress:RoadmapProgress; horizons:Record<RoadmapHorizon,RoadmapAction[]>; milestones:RoadmapMilestone[]; recalibration_notes:string[]; ethical_cautions:string[]; contribution_direction:string; seven_days:RoadmapAction[]; thirty_days:RoadmapAction[]; six_months:RoadmapAction[]; recommended_skills:string[]; ai_workflows:string[]; project_idea:string; social_contribution_idea:string; }
export interface RecalibrationProposal { roadmap_id:string; current_version:number; proposed_version:number; summary:string; changes:Array<{type:string;action_id?:string;action?:Partial<RoadmapAction>;patch?:Partial<RoadmapAction>;reason:string}>; rules_triggered:string[]; ethical_note:string; confidence_note:string; }
