import { Canvas, useFrame } from "@react-three/fiber";
import { useRef } from "react";
import type { Group, Mesh } from "three";
import { useReducedMotionPreference } from "../../hooks/useReducedMotionPreference";
import type { CoachState } from "../../context/CoachContext";

export type AICoachOrbState=CoachState;
const colors:Record<CoachState,string>={idle:"#5eead4",disconnected:"#64748b",connecting:"#38bdf8",listening:"#2dd4bf",transcribing:"#38bdf8",classifying:"#7dd3fc",retrieving:"#84cc16",thinking:"#5eead4",speaking:"#a3e635",muted:"#facc15",executing:"#f8fafc",error:"#f59e0b"};

function OrbMesh({state,reducedMotion}:{state:CoachState;reducedMotion:boolean}){const core=useRef<Mesh>(null);const rings=useRef<Group>(null);const color=colors[state];useFrame(({clock},delta)=>{if(reducedMotion)return;const t=clock.elapsedTime;const fast=["listening","thinking","classifying","retrieving"].includes(state);if(core.current){const pulse=state==="speaking"?Math.sin(t*4)*.055:state==="listening"?Math.sin(t*3)*.07:Math.sin(t*1.4)*.025;core.current.scale.setScalar(1+pulse);core.current.rotation.y+=delta*(fast?.35:.09)}if(rings.current)rings.current.rotation.z+=delta*(state==="thinking"?.45:state==="classifying"?.65:.12)});const ringOpacity=state==="idle"?.28:state==="error"?.35:.72;return <group><mesh ref={core}><sphereGeometry args={[.9,48,48]}/><meshPhysicalMaterial color={color} emissive={color} emissiveIntensity={state==="thinking"?1.2:.72} transmission={.35} transparent opacity={.55} roughness={.12} clearcoat={1}/></mesh><group ref={rings}><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.2,.015,12,160]}/><meshBasicMaterial color={color} transparent opacity={ringOpacity}/></mesh><mesh rotation={[.65,.2,.2]}><torusGeometry args={[1.07,.012,12,160]}/><meshBasicMaterial color={state==="retrieving"?"#a3e635":"#38bdf8"} transparent opacity={ringOpacity*.7}/></mesh>{["thinking","classifying","retrieving","executing"].includes(state)&&<mesh rotation={[.1,Math.PI/2,.4]}><torusGeometry args={[1.34,.01,12,128]}/><meshBasicMaterial color="#dffcf7" transparent opacity={.38}/></mesh>}</group>{state==="retrieving"&&[0,1,2,3].map(i=><mesh key={i} position={[Math.cos(i*Math.PI/2)*1.45,Math.sin(i*Math.PI/2)*1.45,0]}><sphereGeometry args={[.06,16,16]}/><meshBasicMaterial color="#a3e635"/></mesh>)}</group>}

export function AICoachOrb3D({state="idle",className="",onClick}:{state?:CoachState;className?:string;onClick?:()=>void}){const reducedMotion=useReducedMotionPreference();return <button type="button" aria-label={state==="speaking"?"Stop AI speech":`AI Coach status: ${state}`} onClick={onClick} className={className}><Canvas camera={{position:[0,0,4],fov:42}} dpr={[1,1.6]}><ambientLight intensity={.6}/><pointLight position={[2,2,2]} intensity={2.2} color={colors[state]}/><OrbMesh state={state} reducedMotion={reducedMotion}/></Canvas><span className="sr-only">AI Coach is {state}</span></button>}
