import { Html } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { useRef, useState } from "react";
import type { Group } from "three";
import { useReducedMotionPreference } from "../../hooks/useReducedMotionPreference";

export type PotentialNodeSummary = { id: string; title: string; subtitle: string };

function GlobeScene({ nodes, selectedId, onSelect, reducedMotion }: { nodes: PotentialNodeSummary[]; selectedId: string; onSelect: (id: string) => void; reducedMotion: boolean }) {
  const group = useRef<Group>(null);
  const [hovered, setHovered] = useState<string | null>(null);
  useFrame(({ clock }) => { if (group.current && !reducedMotion) group.current.rotation.y = clock.elapsedTime * 0.08; });
  return <group ref={group}><mesh><sphereGeometry args={[1,48,48]} /><meshPhysicalMaterial color="#0f766e" emissive="#5eead4" emissiveIntensity={0.32} transmission={0.35} roughness={0.2} transparent opacity={0.76} /></mesh>{nodes.map((node,index) => { const angle=(index/nodes.length)*Math.PI*2; const position:[number,number,number]=[Math.cos(angle)*2.35,index%2===0?0.72:-0.42,Math.sin(angle)*2.35]; const selected=node.id===selectedId; const active=selected||hovered===node.id; return <group key={node.id} position={position} scale={selected?1.18:1}><mesh rotation={[Math.PI/2,0,0]} visible={selected}><torusGeometry args={[0.43,0.025,12,64]} /><meshStandardMaterial color="#5eead4" emissive="#5eead4" emissiveIntensity={1.2} transparent opacity={0.9} /></mesh><mesh onClick={(event)=>{event.stopPropagation();onSelect(node.id)}} onPointerOver={(event)=>{event.stopPropagation();setHovered(node.id)}} onPointerOut={()=>setHovered(null)}><sphereGeometry args={[0.29,32,32]} /><meshStandardMaterial color={active?"#ffffff":"#dffcf7"} emissive={index%2?"#84cc16":"#38bdf8"} emissiveIntensity={active?0.8:0.28} transparent opacity={selected||!selectedId?1:0.68} /></mesh><Html distanceFactor={8} center><button type="button" aria-pressed={selected} onFocus={()=>setHovered(node.id)} onBlur={()=>setHovered(null)} onClick={()=>onSelect(node.id)} className={`human-potential-globe-label whitespace-nowrap rounded-full border px-3 py-1 text-xs font-semibold backdrop-blur focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[color:var(--color-accent-action-soft)] ${selected?"human-potential-globe-label--selected organic-action-selected":"border-white/25 bg-slate-950/70 text-white"}`}>{node.title}</button></Html></group>; })}</group>;
}

export function HumanPotentialGlobe({ nodes, selectedId, onSelect, centerTitle, centerSubtitle, className="" }: { nodes: PotentialNodeSummary[]; selectedId: string; onSelect: (id: string) => void; centerTitle: string; centerSubtitle: string; className?: string }) {
  const reducedMotion=useReducedMotionPreference();
  return <div className={`relative overflow-hidden rounded-[2.5rem] border border-[color:var(--border-soft)] bg-[color:var(--bg-glass)] ${className}`}><Canvas camera={{position:[0,1.1,6.4],fov:46}} dpr={[1,1.6]}><ambientLight intensity={0.8}/><directionalLight position={[3,4,4]} intensity={1.2}/><pointLight position={[0,1.8,2.5]} intensity={2.2} color="#5eead4"/><GlobeScene nodes={nodes} selectedId={selectedId} onSelect={onSelect} reducedMotion={reducedMotion}/></Canvas><div className="human-potential-globe-center pointer-events-none absolute left-1/2 top-1/2 w-40 -translate-x-1/2 -translate-y-1/2 text-center text-white"><p className="font-display text-2xl font-semibold">You</p><p className="mt-1 text-sm text-[#99f6e4]">{centerTitle}</p><p className="text-xs text-white/70">{centerSubtitle}</p></div><div className="absolute bottom-4 left-4 right-4 rounded-2xl border border-[color:var(--border-soft)] bg-[color:var(--bg-glass)] p-3 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-wider text-[color:var(--teal)]">Accessible node legend</p><div className="mt-2 flex flex-wrap gap-2">{nodes.map(node=><button type="button" key={node.id} aria-pressed={node.id===selectedId} onClick={()=>onSelect(node.id)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[color:var(--color-accent-action-soft)] ${node.id===selectedId?"organic-action-selected":"border-[color:var(--border-soft)] theme-text"}`}>{node.title}</button>)}</div></div></div>;
}
