import { lazy, Suspense, type SyntheticEvent } from "react";
import { ArrowRight, AudioWaveform, BookOpenCheck, BriefcaseBusiness, Compass, Database, GraduationCap, Leaf, Network, Palette, Route, ShieldCheck, Sparkles, UserRoundSearch, Waves } from "lucide-react";
import { Link } from "react-router-dom";
import { AboutCompassFallback } from "../components/three/AboutCompassFallback";
import { OrganicPageBackdrop } from "../components/public/OrganicPageBackdrop";
import { PublicPageShell } from "../components/public/PublicPageShell";
import { ABOUT_ASSETS } from "../config/aboutAssets";
import { useAppActions } from "../hooks/useAppActions";

const AboutCompassScene = lazy(() => import("../components/three/AboutCompassScene").then(module => ({ default: module.AboutCompassScene })));
const imageError=(event:SyntheticEvent<HTMLImageElement>)=>{if(import.meta.env.DEV)console.error("OrganicAI About image failed:",event.currentTarget.src)};
const problems=[
  [Sparkles,"AI is transforming everything","Rapid change reshapes work, learning, and creativity before people have time to understand what it means.","Design implication: begin with human context."],
  [Waves,"Fear and uncertainty are increasing","Anxiety about relevance and the future can make experimentation feel risky and decisions feel urgent.","Research implication: turn uncertainty into reflection."],
  [Network,"Guidance is fragmented","Technical, conflicting, and decontextualized information makes trustworthy next steps difficult to identify.","System implication: connect evidence to personal needs."],
  [Compass,"Loss of direction weakens meaningful action","Without a clear starting point, people can become passive users rather than active partners in change.","Human implication: preserve agency and choice."]
] as const;
const research=[
  ["01","Human-centred AI","Design begins with people, context, capabilities, and human flourishing.","People and context","/research"],
  ["02","Responsible and explainable AI","Recommendations should remain visible, contestable, and accountable.","Trust and ethics","/principles"],
  ["03","Recommendation systems and personalization","Guidance becomes useful when relevance does not become manipulation.","Relevance and fit","/how-it-works"],
  ["04","Voice interaction and accessibility","Natural interaction should expand access while preserving consent and privacy.","Inclusive interaction","/research"]
] as const;

export function AboutPage(){
  document.title="OrganicAI Compass - About"; const { activeProfileId: profile }=useAppActions();
  const coachPath=profile?`/coach/${profile}`:"/diagnostic";
  const roadmapPath=profile?`/roadmap/${profile}`:"/diagnostic";
  const modules=[
    [UserRoundSearch,"Human Diagnostic","Discover strengths, values, and AI fluency through structured reflection.","A human starting point","/diagnostic","teal"],
    [Database,"RAG Knowledge Base","Explore curated, research-informed knowledge grounded in your evolving context.","Source-visible knowledge","/knowledge-base","cyan"],
    [AudioWaveform,"Voice AI Coach","Use natural conversation to clarify, challenge, and guide your thinking.","Reflective dialogue",coachPath,"violet"],
    [Route,"Personalized Roadmap","Turn insight into editable recommendations and meaningful next steps.","Purpose-aligned action",roadmapPath,"green"]
  ] as const;
  const audiences=[
    [BriefcaseBusiness,"Professionals navigating AI change","Build confidence, understand changing capabilities, and make purposeful career decisions.","Clarity, adaptation, and informed action","/diagnostic"],
    [GraduationCap,"Students and lifelong learners","Develop future-ready strengths and choose learning paths with greater context.","Curiosity and future-ready learning","/learning-paths"],
    [Palette,"Designers, creators, and interdisciplinary innovators","Explore new possibilities while keeping human intent at the centre of co-creation.","Meaningful human–AI co-creation","/co-creation-studio"]
  ] as const;
  return <PublicPageShell><div className="about-page"><OrganicPageBackdrop/><div className="about-page-container">
    <section className="about-hero" aria-labelledby="about-title"><div className="about-hero-copy"><p className="about-eyebrow">ABOUT ORGANICAI COMPASS</p><h1 id="about-title">A <em>human-centred</em> compass<br/>for the age of AI</h1><p className="about-hero-lead">OrganicAI Compass helps people understand their strengths, transform uncertainty about AI, and create a meaningful path for human–AI collaboration.</p><div className="about-actions"><Link className="about-button" to="/diagnostic">Start Your Diagnostic <ArrowRight size={17}/></Link><Link className="about-button secondary" to="/how-it-works">See How It Works</Link></div><div className="about-hero-links"><Link to="/research">Explore the Research</Link><Link to="/principles">Read the Principles</Link></div><div className="about-chips"><span><BookOpenCheck size={15}/> Research-informed</span><span><ShieldCheck size={15}/> Human agency first</span></div></div><div className="about-hero-scene"><img src={ABOUT_ASSETS.hero} alt="" aria-hidden="true" onError={imageError}/><div className="about-scene-shade"/><Suspense fallback={<AboutCompassFallback/>}><AboutCompassScene/></Suspense></div></section>
    <section className="about-section about-mission" aria-labelledby="mission-title"><div><p className="about-eyebrow">OUR PURPOSE</p><h2 id="mission-title">Technology should strengthen human capacity.</h2></div><blockquote>OrganicAI Compass is built around a simple belief: artificial intelligence should help people understand themselves, expand their capabilities, and make informed choices—not replace their judgment or define their future.</blockquote></section>
    <section className="about-section about-why" aria-labelledby="why-title"><header className="about-heading"><p className="about-eyebrow">WHY ORGANICAI COMPASS EXISTS</p><h2 id="why-title">AI is transforming everything,<br/>but people are often left without a compass.</h2><p>People face uncertainty, fragmented information, loss of direction, and fear of making the wrong decisions. OrganicAI brings those concerns into one reflective journey.</p></header><div className="about-problem-grid">{problems.map(([Icon,title,text,note],i)=><article key={title}><div><span>0{i+1}</span><Icon size={26}/></div><h3>{title}</h3><p>{text}</p><small>{note}</small></article>)}</div></section>
    <section className="about-section about-fear" aria-labelledby="fear-title"><div className="about-fear-image"><img src={ABOUT_ASSETS.transformation} alt="An atmospheric pathway from uncertainty toward purposeful human and AI collaboration" loading="lazy" onError={imageError}/></div><div className="about-fear-copy"><p className="about-eyebrow">A HUMAN TRANSFORMATION</p><h2 id="fear-title">From fear to agency</h2><div className="about-state"><small>OLD PARADIGM</small><h3>Technology-led</h3><p>Automation-first · Fear-driven decisions · Opaque recommendations · Passive dependence</p></div><ol>{["Reflection","Understanding","Choice","Action","Feedback","Adaptation"].map(step=><li key={step}>{step}</li>)}</ol><div className="about-state new"><small>NEW PARADIGM</small><h3>Human-led collaboration</h3><p>Visible evidence · Editable recommendations · Meaningful learning · Purpose-aligned action</p></div></div></section>
    <section className="about-section about-platform" aria-labelledby="platform-title"><header className="about-heading"><p className="about-eyebrow">WHAT THE PLATFORM COMBINES</p><h2 id="platform-title">One journey connecting reflection,<br/>grounded knowledge, guidance, and action</h2></header><div className="about-module-grid">{modules.map(([Icon,title,text,capability,to,accent])=><article className={`accent-${accent}`} key={title}><span className="about-module-icon"><Icon size={28}/></span><h3>{title}</h3><p>{text}</p><small>KEY CAPABILITY</small><b>{capability}</b><Link to={to}>Explore module <ArrowRight size={15}/></Link></article>)}</div></section>
    <section className="about-section about-research" aria-labelledby="research-title"><header><p className="about-eyebrow">RESEARCH-INFORMED, NOT TECHNOLOGY-LED</p><h2 id="research-title">Technology follows human needs,<br/>not the other way around</h2><p>The platform connects established research concerns to design decisions that can be inspected and evaluated.</p></header><div className="about-principles">{research.map(([n,title,text,focus,to])=><article key={title}><span>{n}</span><h3>{title}</h3><p>{text}</p><small>Research focus: {focus}</small><Link to={to}>Explore <ArrowRight size={14}/></Link></article>)}</div><div className="about-evidence"><span><b>IMPLEMENTED</b> Prototype journey</span><span><b>IMPLEMENTED</b> Curated RAG workflow</span><span><b>READY FOR API TESTING</b> Voice architecture</span><span><b>READY FOR EVALUATION</b> Evaluation framework</span></div></section>
    <section className="about-section about-audience" aria-labelledby="audience-title"><header className="about-heading"><p className="about-eyebrow">WHO IT IS FOR</p><h2 id="audience-title">Designed for people navigating<br/>change, growth, and collaboration</h2></header><div className="about-audience-grid">{audiences.map(([Icon,title,text,outcome,to])=><article key={title}><div className="about-portrait"><Icon size={54}/><i/><i/></div><h3>{title}</h3><p>{text}</p><b>{outcome}</b><Link to={to}>Suggested starting point <ArrowRight size={15}/></Link></article>)}</div></section>
    <section className="about-section about-manifesto" aria-labelledby="manifesto-title"><img src={ABOUT_ASSETS.finalCta} alt="" aria-hidden="true" loading="lazy" onError={imageError}/><div><p className="about-eyebrow">DESIGNED FOR A MEANINGFUL HUMAN–AI FUTURE</p><h2 id="manifesto-title">Your future with AI should be designed,<br/>not merely predicted.</h2><p>OrganicAI Compass helps turn uncertainty into reflection, reflection into informed choices, and choices into meaningful action.</p></div></section>
    <section className="about-final" aria-labelledby="final-title"><div><p className="about-eyebrow">BEGIN THE JOURNEY</p><h2 id="final-title">Begin with reflection.<br/>Continue with grounded action.</h2><div className="about-actions"><Link className="about-button" to="/diagnostic">Start Diagnostic <ArrowRight size={17}/></Link><Link className="about-button secondary" to="/how-it-works">Explore How It Works</Link><Link className="about-text-link" to="/research">Read the Research</Link></div></div><div className="about-css-compass" aria-hidden="true"><Compass size={54}/><i/><i/></div></section>
  </div></div></PublicPageShell>;
}
