import { ArrowRight, BookOpen, CheckCircle2, FileText, Leaf, Mail, Network, Search, Sparkles, X } from "lucide-react";
import { type FormEvent, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { OrganicPageBackdrop } from "../components/public/OrganicPageBackdrop";
import { PublicPageShell } from "../components/public/PublicPageShell";
import { blogArticles, blogCategories, type BlogArticle, type BlogCategory } from "../data/blogArticles";
import "../styles/blog.css";

function ArticleVisual({article,large=false}:{article:BlogArticle;large?:boolean}){return <div className={`blog-article-visual variant-${article.heroVariant} ${large?"large":""}`} aria-hidden="true"><span className="visual-core"><Leaf/><b>{article.category}</b></span><i/><i/><i/><em>“</em></div>}
function ArticleCard({article}:{article:BlogArticle}){return <article className={`blog-article-card accent-${article.heroVariant}`} data-article-slug={article.slug}><ArticleVisual article={article}/><div><p className="blog-card-meta"><span>{article.contentType}</span><span>{article.category}</span></p><h3>{article.title}</h3><p>{article.excerpt}</p><div className="blog-module-chips">{article.relatedRoutes.map(route=><span key={route.to}>{route.label}</span>)}</div><div className="blog-card-actions"><span>{article.readingTime}</span><Link to={`/blog/${article.slug}`}>Read Article <ArrowRight size={15}/></Link></div></div></article>}
function Collection({eyebrow,description,articles}:{eyebrow:string;description:string;articles:BlogArticle[]}){return <section className="blog-collection"><header><p>{eyebrow}</p><h2>{description}</h2></header><div>{articles.map(article=><Link key={article.slug} to={`/blog/${article.slug}`}><span>{article.contentType}</span><b>{article.title}</b><small>{article.readingTime}</small><ArrowRight size={16}/></Link>)}</div></section>}

export function BlogPage(){
  document.title="OrganicAI Compass - Journal";
  const [query,setQuery]=useState("");const [category,setCategory]=useState<"All"|BlogCategory>("All");const [email,setEmail]=useState("");const [newsletter,setNewsletter]=useState("");
  const featured=blogArticles.find(article=>article.featured)!;
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return blogArticles.filter(article=>(category==="All"||article.category===category)&&(!needle||[article.title,article.excerpt,article.category,article.contentType].some(value=>value.toLowerCase().includes(needle))))},[query,category]);
  const clear=()=>{setQuery("");setCategory("All")};
  function submitNewsletter(event:FormEvent){event.preventDefault();setNewsletter(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?"Thank you. Newsletter delivery is not connected in this research prototype yet.":"Enter a valid email address to test this prototype form.");}
  return <PublicPageShell><div className="organicai-blog-page"><OrganicPageBackdrop/><div className="organicai-blog-container">
    <section className="organicai-blog-hero" aria-labelledby="blog-title"><div className="blog-hero-copy"><p className="blog-eyebrow">ORGANICAI RESEARCH JOURNAL</p><h1 id="blog-title">Ideas, evidence, and reflections for meaningful human–AI collaboration</h1><p>Explore research notes, technical explainers, design decisions, and responsible AI perspectives emerging from the development of OrganicAI Compass.</p><div className="blog-status-chips"><span>HUMAN-CENTRED AI</span><span>RESEARCH + DESIGN + ENGINEERING</span><span>OPEN DEVELOPMENT JOURNAL</span></div><div className="blog-actions"><a className="blog-button" href="#featured-article">Read the Featured Article</a><Link className="blog-button secondary" to="/research">Explore the Research</Link><Link className="blog-text-link" to="/project-roadmap">View Project Roadmap</Link></div></div><div className="blog-hero-visual" role="img" aria-label="OrganicAI Journal connected to six editorial themes"><div className="journal-sphere"><BookOpen/><b>JOURNAL</b><small>ideas into evidence</small></div>{["HUMAN-CENTRED AI","RAG","VOICE","AGENCY","FUTURE OF WORK","BUILDING THE PROTOTYPE"].map((theme,index)=><span className={`journal-leaf leaf-${index}`} key={theme}><FileText size={13}/>{theme}</span>)}<i/><i/><i/><em>“</em></div></section>
    <section className="blog-status-strip" aria-label="Journal facts">{["6 foundational articles","6 research and design themes","Public dissertation journal","Content grounded in the implemented prototype"].map(item=><span key={item}><CheckCircle2 size={16}/>{item}</span>)}</section>
    <section id="featured-article" className="blog-section"><header className="blog-section-heading"><p>FEATURED RESEARCH NOTE</p><h2>A contextual starting point for the Journal</h2></header><article className="blog-featured"><ArticleVisual article={featured} large/><div><p className="blog-card-meta"><span>{featured.contentType}</span><span>{featured.category}</span></p><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="blog-module-chips">{featured.relatedRoutes.map(route=><span key={route.to}>{route.label}</span>)}</div><span>{featured.readingTime}</span><Link className="blog-button" to={`/blog/${featured.slug}`}>Read Article <ArrowRight size={16}/></Link></div></article></section>
    <section className="blog-section blog-discovery" aria-labelledby="latest-notes"><header className="blog-section-heading"><p>JOURNAL LIBRARY</p><h2 id="latest-notes">Latest research notes</h2></header><label className="blog-search"><Search size={18}/><span>Search the OrganicAI Journal</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the OrganicAI Journal"/></label><div className="blog-filters" aria-label="Journal categories">{blogCategories.map(item=><button type="button" key={item} aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="blog-results-summary"><span>Showing {filtered.length} {filtered.length===1?"article":"articles"}</span>{(query||category!=="All")&&<button type="button" onClick={clear}><X size={14}/> Clear filters</button>}</div>{filtered.length?<div className="blog-grid">{filtered.map(article=><ArticleCard article={article} key={article.slug}/>)}</div>:<div className="blog-empty"><Search size={28}/><h3>No journal entries match this search.</h3><p>Try another term or reset the active category.</p><button className="blog-button" type="button" onClick={clear}>Show all articles</button></div>}</section>
    <Collection eyebrow="HUMAN-CENTRED AI" description="Research and design perspectives on agency, strengths, values, and meaningful collaboration." articles={blogArticles.filter(a=>a.category==="Human-Centred AI"||a.category==="Future of Work")}/>
    <Collection eyebrow="BUILDING ORGANICAI" description="Technical and project notes from the development of the dissertation prototype." articles={blogArticles.filter(a=>a.category==="Building OrganicAI"||a.category==="RAG & Knowledge")}/>
    <Collection eyebrow="RESPONSIBLE AI" description="Transparency, privacy, voice, trust, and bounded system behaviour." articles={blogArticles.filter(a=>a.category==="Responsible AI"||a.category==="Voice & Interaction")}/>
    <section className="blog-newsletter"><div><p>NEWSLETTER PROTOTYPE</p><h2>Follow the OrganicAI research journey</h2><span>Receive new research notes, implementation insights, and responsible AI reflections as the prototype evolves.</span></div><form onSubmit={submitNewsletter} noValidate><label htmlFor="journal-email">Email address</label><div><Mail size={18}/><input id="journal-email" value={email} onChange={event=>setEmail(event.target.value)} type="email" placeholder="you@example.com"/><button type="submit">Follow the Journal</button></div>{newsletter&&<p role="status">{newsletter}</p>}</form></section>
  </div></div></PublicPageShell>;
}
