import { useEffect,useRef,useState,type ComponentType } from "react";
import { ArrowRight,AudioWaveform,BookOpenCheck,BriefcaseBusiness,Compass,Database,GraduationCap,Lightbulb,Network,Palette,Pause,Play,Route,ShieldCheck,Sparkles,Target,UserRoundSearch } from "lucide-react";
import { Link } from "react-router-dom";
import { getActiveProfileId } from "../lib/activeProfile";

const media={hero:"/images/organicai-hero-human-ai-bg-v2.png",human:"/images/about/about-hero-environment.png",grounded:"/images/about/about-fear-to-agency.png",voice:"/images/organicai-hero-human-ai-bg.png",roadmap:"/images/about/about-final-cta.png"};
type Story={eyebrow:string;title:string;body:string;points:string[];image:string;alt:string;primary:[string,string];secondary?:[string,string];reverse?:boolean;status?:string};
function StorySection({story}:{story:Story}){return <section className={`home-story ${story.reverse?"reverse":""}`}><div className="home-story-media"><img src={story.image} alt={story.alt} width="1200" height="900" loading="lazy"/><div className="home-media-motif" aria-hidden="true"><i/><i/><span>{story.status||"ORGANICAI COMPASS"}</span></div></div><div className="home-story-copy"><p className="home-eyebrow">{story.eyebrow}</p><h2>{story.title}</h2><p>{story.body}</p><ul>{story.points.map(point=><li key={point}><span>✓</span>{point}</li>)}</ul><div className="home-links"><Link className="home-button" to={story.primary[1]}>{story.primary[0]} <ArrowRight size={16}/></Link>{story.secondary&&<Link to={story.secondary[1]}>{story.secondary[0]}</Link>}</div></div></section>}
function HomeHero(){const video=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(false);const [posterOnly,setPosterOnly]=useState(false);useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const saveData=Boolean((navigator as Navigator&{connection?:{saveData?:boolean}}).connection?.saveData);setPosterOnly(reduced||saveData);if(!reduced&&!saveData)video.current?.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))},[]);const toggle=()=>{if(!video.current||posterOnly)return;if(video.current.paused)video.current.play().then(()=>setPlaying(true));else{video.current.pause();setPlaying(false)}};return <><section className="home-hero" aria-labelledby="home-title"><video ref={video} muted loop playsInline preload="metadata" poster={media.hero} aria-label="OrganicAI human and artificial intelligence landscape" onError={()=>setPlaying(false)}>{!posterOnly&&<><source src="/videos/home/organicai-home-hero.webm" type="video/webm"/><source src="/videos/home/organicai-home-hero.mp4" type="video/mp4"/></>}</video><div className="home-hero-overlay"/><div className="home-hero-copy"><p className="home-eyebrow">HUMAN-CENTRED AI FOR MEANINGFUL ACTION</p><h1 id="home-title">Design your future.<br/><em>Together with AI.</em></h1><p>OrganicAI Compass helps you understand your strengths, explore your relationship with artificial intelligence, receive grounded guidance, and turn reflection into meaningful action.</p><div className="home-hero-actions"><Link className="home-button" to="/diagnostic">Start Your Diagnostic <ArrowRight size={17}/></Link><Link className="home-button secondary" to="/how-it-works">See How It Works</Link><button type="button" onClick={toggle} aria-label={playing?"Pause overview video":"Play overview video"}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?"Pause Overview":"Play Overview"}</button></div><Link className="home-research-link" to="/research">Explore the Research <ArrowRight size={14}/></Link></div></section><div className="home-value-strip">{[[UserRoundSearch,"Understand Yourself","Begin with your human context."],[Database,"Ground AI in Knowledge","Connect guidance to visible sources."],[Route,"Turn Insight into Action","Build an editable path forward."],[Sparkles,"Grow with Confidence","Reflect, adapt, and retain agency."]].map(([Icon,title,text])=><article key={title as string}><Icon size={22}/><div><b>{title as string}</b><span>{text as string}</span></div></article>)}</div></>}

export function LandingPage(){document.title="OrganicAI Compass - Design your future with AI";const profile=getActiveProfileId();const stories:Story[]=[
  {eyebrow:"BEGIN WITH THE HUMAN",title:"Understand yourself before asking AI what to do",body:"The Human Diagnostic creates a reflective starting point shaped by your talents, values, interests, concerns, goals, and preferred ways of learning and collaborating.",points:["You control and can revise your profile","Strengths and values remain visible","Reflection comes before recommendation"],image:media.human,alt:"Human-centred environment representing strengths, values, and purpose",primary:["Explore the Diagnostic","/diagnostic"],secondary:["View Human Potential Map",`/profile/${profile}`]},
  {eyebrow:"GROUND GUIDANCE IN KNOWLEDGE",title:"More than an answer: guidance with visible context",body:"A curated Knowledge Base and semantic retrieval workflow provide context for RAG-supported answers. Sources, confidence notes, ethical considerations, and limitations remain visible; retrieval reduces uncertainty but does not eliminate errors.",points:["Curated documents and semantic retrieval","Source-visible grounded responses","Transparent limitations and ethical notes"],image:media.grounded,alt:"Luminous path connecting knowledge fragments into grounded guidance",primary:["Open Knowledge Base","/knowledge-base"],secondary:["Read the Research","/research"],reverse:true},
  {eyebrow:"A MORE NATURAL INTERACTION",title:"Speak, reflect, and remain in control",body:"The AI Coach supports text and a voice-response architecture with visible listening, thinking, and speaking states. Microphone input, transcript confirmation, consent, privacy, and editing remain part of the interaction design.",points:["Review and edit before sending","Visible system and transcript states","Consent-aware voice architecture"],image:media.voice,alt:"Human and AI forms connected through a reflective voice interaction",primary:["Open AI Coach",`/coach/${profile}`],secondary:["Read the Principles","/principles"],status:"READY FOR API TESTING"},
  {eyebrow:"FROM INSIGHT TO ACTION",title:"Build a path that evolves with you",body:"Personalized recommendations connect reflection to seven-day steps, thirty-day development, and longer-term objectives. Recommendations remain editable, rejectable, and open to recalibration as priorities change.",points:["Practical near-term steps","Longer-term, purpose-aligned objectives","Progress without fake certainty"],image:media.roadmap,alt:"Organic pathway representing an adaptable personalized roadmap",primary:["Explore How It Works","/how-it-works"],secondary:["Open Your Roadmap",`/roadmap/${profile}`],reverse:true}
];
const journey=[[Target,"Define your intention","Name the change or question that matters.","/diagnostic"],[UserRoundSearch,"Complete the Human Diagnostic","Reflect on strengths, values, and AI fluency.","/diagnostic"],[Compass,"Explore your Human Potential Map","Review and revise the interpretation.",`/profile/${profile}`],[AudioWaveform,"Speak with the AI Coach","Use grounded dialogue to explore options.",`/coach/${profile}`],[Lightbulb,"Review recommendations","Accept, edit, or reject suggested actions.",`/recommendations/${profile}`],[Route,"Build and adapt your roadmap","Turn choices into an evolving plan.",`/roadmap/${profile}`]] as const;
return <div className="home-page"><div className="home-page-container"><HomeHero/>
  <section className="home-mission"><div><p className="home-eyebrow">A DIFFERENT RELATIONSHIP WITH AI</p><h2>Technology should strengthen human capacity.</h2></div><blockquote>Artificial intelligence should not define who you are or decide your future. It should help you understand your strengths, expand your choices, and act with greater clarity.</blockquote></section>
  <div className="home-stories">{stories.map(story=><StorySection story={story} key={story.title}/>)}</div>
  <section className="home-section home-journey"><header><p className="home-eyebrow">THE ORGANICAI JOURNEY</p><h2>From reflection to meaningful action</h2></header><div>{journey.map(([Icon,title,text,to],i)=><article key={title}><span>0{i+1}</span><Icon size={25}/><h3>{title}</h3><p>{text}</p><Link to={to}>Continue <ArrowRight size={14}/></Link></article>)}</div></section>
  <section className="home-section home-responsible"><div><p className="home-eyebrow">RESEARCH-INFORMED, RESPONSIBLE BY DESIGN</p><h2>A system built to support agency,<br/>not replace judgment</h2><p>Human-centred design, RAG transparency, recommendation relevance, voice accessibility, bounded claims, and an evaluation framework shape the implemented prototype.</p><div className="home-links"><Link className="home-button" to="/research">Explore the Research</Link><Link to="/principles">Read the Principles</Link><Link to="/project-roadmap">View Project Roadmap</Link></div></div><div className="home-principles">{[[UserRoundSearch,"Human-centred","Context precedes automation."],[BookOpenCheck,"Grounded","Knowledge and sources stay visible."],[ShieldCheck,"Transparent","Limits and uncertainty are explicit."],[Route,"Adaptable","People can revise the path."]].map(([Icon,title,text])=><article key={title as string}><Icon size={24}/><h3>{title as string}</h3><p>{text as string}</p></article>)}</div><div className="home-evidence"><span><b>IMPLEMENTED PROTOTYPE</b> Connected public and workspace journey</span><span><b>TECHNICALLY VERIFIED</b> Local software verification</span><span><b>RAG WORKFLOW AVAILABLE</b> Curated retrieval architecture</span><span><b>VOICE READY FOR API TESTING</b> Integration architecture</span><small>Software verification is not empirical user validation.</small></div></section>
  <section className="home-section home-audience"><header><p className="home-eyebrow">DESIGNED FOR PEOPLE IN TRANSITION</p><h2>For people navigating change,<br/>learning, creativity, and collaboration</h2></header><div>{[[BriefcaseBusiness,"Professionals adapting to AI","Clarify changing capabilities and make purposeful career decisions.","/diagnostic"],[GraduationCap,"Students and lifelong learners","Build future-ready strengths and choose learning paths with context.","/learning-paths"],[Palette,"Designers, creators, and interdisciplinary innovators","Co-create while keeping human intent and judgment at the centre.","/co-creation-studio"]].map(([Icon,title,text,to])=><article key={title as string}><div><Icon size={48}/><i/></div><h3>{title as string}</h3><p>{text as string}</p><Link to={to as string}>Recommended starting action <ArrowRight size={14}/></Link></article>)}</div></section>
  <section className="home-section home-prototype"><header><p className="home-eyebrow">EXPLORE THE PROTOTYPE</p><h2>See how the OrganicAI experience connects</h2></header><div>{[[UserRoundSearch,"Human Diagnostic","Structured reflection creates a meaningful starting point.","/diagnostic",media.human],[Compass,"Human Potential Map","A visible, revisable interpretation of your human context.",`/profile/${profile}`,media.hero],[AudioWaveform,"AI Coach","Grounded text and voice-ready reflective interaction.",`/coach/${profile}`,media.voice],[Route,"Personalized Roadmap","Editable recommendations connect insight to action.",`/roadmap/${profile}`,media.roadmap]].map(([Icon,title,text,to,image])=><article key={title as string}><div><img src={image as string} alt="" loading="lazy"/><Icon size={30}/><span>IMPLEMENTED PROTOTYPE</span></div><h3>{title as string}</h3><p>{text as string}</p><Link to={to as string}>Open module <ArrowRight size={14}/></Link></article>)}</div></section>
  <section className="home-manifesto"><img src={media.roadmap} alt="" aria-hidden="true" loading="lazy"/><div><p className="home-eyebrow">A HUMAN-CENTRED FUTURE</p><h2>Your future with AI should be designed,<br/>not merely predicted.</h2><p>OrganicAI Compass helps transform uncertainty into reflection, reflection into informed choices, and choices into meaningful action.</p></div></section>
  <section className="home-final"><div><p className="home-eyebrow">YOUR NEXT STEP</p><h2>Begin with reflection.<br/>Continue with grounded action.</h2><div className="home-links"><Link className="home-button" to="/diagnostic">Start Your Diagnostic <ArrowRight size={16}/></Link><Link to="/how-it-works">Explore How It Works</Link><Link to="/research">Read the Research</Link><Link to="/blog">Open the Journal</Link></div></div><div className="home-css-compass" aria-hidden="true"><Compass size={58}/><i/><i/></div></section>
</div></div>}
