import { ArrowRight, BriefcaseBusiness, Download, Layers3, RefreshCw, Share2, Sparkles, UserRound } from "lucide-react";
import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getAssessmentResults, getCareerMatches } from "../api/assessmentApi";
import { getProfile, getProfileFeedback, updateProfileFeedback } from "../api/profileApi";
import { PotentialNodeDetailPanel, type PotentialNodeDetail } from "../components/profile/PotentialNodeDetailPanel";
import type { PotentialNodeSummary } from "../components/three/HumanPotentialGlobe";
import { useAppActions } from "../hooks/useAppActions";
import type { AssessmentResults, CareerMatch } from "../types/assessment";
import type { HumanPotentialProfile, ProfileUserFeedback } from "../types/profile";
import { useCoach } from "../hooks/useCoach";

const HumanPotentialGlobe=lazy(()=>import("../components/three/HumanPotentialGlobe").then(module=>({default:module.HumanPotentialGlobe})));
const emptyFeedback:ProfileUserFeedback={confirmed_nodes:[],hidden_recommendations:[],strength_adjustments:{},archetype_override:null,user_notes:{}};

function average(values:number[]){return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null}

export function ProfilePage(){
  const {id}=useParams(); const navigate=useNavigate(); const {setActiveProfileId}=useAppActions();
  const {setSelectedProfileNode}=useCoach();
  const [profile,setProfile]=useState<HumanPotentialProfile|null>(null); const [feedback,setFeedback]=useState<ProfileUserFeedback>(emptyFeedback); const [selectedId,setSelectedId]=useState("talents"); const [error,setError]=useState(""); const [status,setStatus]=useState(""); const [mapLayer,setMapLayer]=useState("human-potential"); const [assessmentResults,setAssessmentResults]=useState<AssessmentResults|null>(null); const [careerMatches,setCareerMatches]=useState<CareerMatch[]>([]);
  useEffect(()=>{if(!id)return;Promise.all([getProfile(id),getProfileFeedback(id)]).then(([data,saved])=>{setProfile(data);setFeedback(saved);setActiveProfileId(data.id)}).catch(()=>setError("This Human Potential Profile could not be loaded."))},[id,setActiveProfileId]);
  useEffect(()=>{if(!id)return;Promise.all([getAssessmentResults(id).catch(()=>null),getCareerMatches(id).catch(()=>[])]).then(([results,matches])=>{setAssessmentResults(results);setCareerMatches(matches)})},[id]);
  useEffect(()=>{setSelectedProfileNode(selectedId);return()=>setSelectedProfileNode(null)},[selectedId,setSelectedProfileNode]);
  async function saveFeedback(next:ProfileUserFeedback){if(!profile)return;const saved=await updateProfileFeedback(profile.id,next);setFeedback(saved);setStatus("Your interpretation settings were saved.")}
  async function share(){try{if(navigator.share){await navigator.share({title:"My OrganicAI Human Potential Map",url:location.href});setStatus("Profile shared successfully.")}else{await navigator.clipboard.writeText(location.href);setStatus("Profile link copied.")}}catch{setStatus("Sharing was cancelled or unavailable.")}}
  const nodes=useMemo<PotentialNodeSummary[]>(()=>{if(!profile)return[];if(mapLayer==="personality")return Object.values(assessmentResults?.grouped_scores?.personality||{}).map(x=>({id:`personality-${x.dimension}`,title:x.dimension.replace(/_/g," "),subtitle:x.label}));if(mapLayer==="career-interests")return Object.values(assessmentResults?.grouped_scores?.career_interest||{}).map(x=>({id:`interest-${x.dimension}`,title:x.dimension.replace(/_/g," "),subtitle:x.label}));if(mapLayer==="work-values")return (assessmentResults?.summary?.top_work_values||[]).map(x=>({id:`value-${x.value}`,title:x.label,subtitle:"User-rated priority"}));if(mapLayer==="skills-evidence")return (assessmentResults?.summary?.skills||[]).filter(x=>x.level>=2).slice(0,8).map(x=>({id:`skill-${x.skill_id}`,title:x.label,subtitle:`${x.level_label} - ${x.evidence_status.replace(/_/g," ")}`}));if(mapLayer==="ai-readiness")return[{id:"ai-literacy",title:"AI Literacy",subtitle:assessmentResults?.summary?.ai_literacy_level||"Emerging"},{id:"ai-readiness",title:"AI Readiness",subtitle:assessmentResults?.summary?.ai_readiness_level||"Emerging"},{id:"change-readiness",title:"Change Readiness",subtitle:assessmentResults?.summary?.change_readiness||"Exploring options"}];if(mapLayer==="career-compatibility")return careerMatches.slice(0,7).map(x=>({id:`career-${x.id}`,title:x.title,subtitle:x.alignment_label}));return[{id:"talents",title:"Talents",subtitle:profile.strengths.slice(0,2).map(x=>x.name).join(" · ")},{id:"values",title:"Values",subtitle:profile.values.slice(0,2).map(x=>x.name).join(" · ")},{id:"creativity",title:"Creativity",subtitle:profile.creative_tendencies[0]||"Exploration"},{id:"ai-collaboration",title:"AI Collaboration",subtitle:profile.ai_collaboration_style.name},{id:"contribution",title:"Contribution Domains",subtitle:profile.contribution_domains[0]?.name||"Emerging"},{id:"learning",title:"Learning Paths",subtitle:profile.recommended_learning_paths[0]?.name||"Emerging"},{id:"next-steps",title:"Next Steps",subtitle:"Personal roadmap"}]},[assessmentResults,careerMatches,mapLayer,profile]);
  useEffect(()=>{if(nodes.length&&!nodes.some(node=>node.id===selectedId))setSelectedId(nodes[0].id)},[nodes,selectedId]);
  const details=useMemo<Record<string,PotentialNodeDetail>>(()=>{if(!profile)return {} as Record<string,PotentialNodeDetail>;const common=profile.primary_archetype.signals;return{
    talents:{id:"talents",title:"Possible Strengths",interpretation:profile.strengths.map(x=>x.explanation).join(" "),confidence:average(profile.strengths.map(x=>x.score))!/100,signals:profile.strengths.map(x=>x.name),evidence:profile.strengths.flatMap(x=>x.evidence),actions:["Use one strength in a small AI-supported experiment","Record where your judgment added value"],caution:"You decide which strengths feel accurate and how much importance they deserve."},
    values:{id:"values",title:"Values",interpretation:"Your selected values provide a human-led filter for technology decisions.",confidence:average(profile.values.map(x=>x.score))!/100,signals:profile.values.map(x=>x.name),evidence:profile.values.flatMap(x=>x.evidence),actions:["Write one non-negotiable AI boundary","Use your values to review an AI output"],caution:"Personal values cannot be delegated to an automated system."},
    creativity:{id:"creativity",title:"Creative Tendencies",interpretation:profile.creative_tendencies.join(". "),signals:profile.creative_tendencies,evidence:common,actions:["Create three variations, then choose one yourself","Turn one idea into a small artifact"],caution:"Authorship, taste, and meaning remain yours."},
    "ai-collaboration":{id:"ai-collaboration",title:profile.ai_collaboration_style.name,interpretation:profile.ai_collaboration_style.summary,confidence:profile.primary_archetype.confidence,signals:profile.ai_collaboration_style.strengths,evidence:common,actions:profile.ai_collaboration_style.recommended_uses,caution:profile.ai_collaboration_style.human_led_decisions.join(", ")},
    contribution:{id:"contribution",title:"Contribution Domains",interpretation:profile.contribution_domains.map(x=>x.explanation).join(" "),confidence:average(profile.contribution_domains.map(x=>x.score))!/100,signals:profile.contribution_domains.map(x=>x.name),evidence:[...profile.values.map(x=>x.name),...common],actions:["Choose one community need","Design a one-week contribution experiment"],caution:"Communities should help define what useful contribution means."},
    learning:{id:"learning",title:"Learning Paths",interpretation:"These paths connect your current signals with safe, practical growth.",signals:profile.recommended_learning_paths.map(x=>x.name),evidence:common,actions:profile.recommended_learning_paths.map(x=>`${x.name}: ${x.reason}`),caution:"Hide or replace any recommendation that does not fit your goals."},
    "next-steps":{id:"next-steps",title:"Next Steps",interpretation:"Move from interpretation to one small, reversible experiment.",signals:common,evidence:profile.creative_tendencies,actions:["Open your roadmap","Run a 15-minute AI collaboration experiment","Reflect and adjust your map"],caution:"Progress is self-directed; this map is guidance, not destiny."}
  }},[profile]);
  const enrichedDetails=useMemo<Record<string,PotentialNodeDetail>>(()=>({
    ...details,
    ...Object.fromEntries(Object.values(assessmentResults?.grouped_scores?.personality||{}).map(x=>[`personality-${x.dimension}`,{id:`personality-${x.dimension}`,title:x.dimension.replace(/_/g," "),interpretation:x.interpretation,confidence:x.normalized_score/100,signals:[x.label],evidence:["Calculated from self-reported Likert responses"],actions:["Review whether this tendency feels accurate","Retake the module if context changed"],caution:"This is non-clinical and not a permanent label."}])),
    ...Object.fromEntries(Object.values(assessmentResults?.grouped_scores?.career_interest||{}).map(x=>[`interest-${x.dimension}`,{id:`interest-${x.dimension}`,title:x.dimension.replace(/_/g," "),interpretation:x.interpretation,confidence:x.normalized_score/100,signals:[x.label],evidence:["Calculated from preferred activity responses"],actions:["Compare this interest with real job activities","Run a small experiment before deciding"],caution:"Interest alignment is not the same as capability or employability."}])),
    ...Object.fromEntries((assessmentResults?.summary?.top_work_values||[]).map(x=>[`value-${x.value}`,{id:`value-${x.value}`,title:x.label,interpretation:`${x.label} is currently a high-priority work value.`,confidence:x.normalized_score/100,signals:["Self-reported value priority"],evidence:["User-rated importance"],actions:["Check career options for value conflicts","Adjust value priority if it no longer fits"],caution:"Values can conflict; the system should show those tensions."}])),
    ...Object.fromEntries((assessmentResults?.summary?.skills||[]).map(x=>[`skill-${x.skill_id}`,{id:`skill-${x.skill_id}`,title:x.label,interpretation:`Self-reported level: ${x.level_label}. Evidence status: ${x.evidence_status.replace(/_/g," ")}.`,signals:[x.category],evidence:[x.evidence_note||x.evidence_status],actions:["Add stronger evidence if available","Use this skill in a small career experiment"],caution:"Self-reported skills are not treated as objectively verified."}])),
    "ai-literacy":{id:"ai-literacy",title:"AI Literacy",interpretation:`Current level: ${assessmentResults?.summary?.ai_literacy_level||"Emerging"}.`,signals:["Conceptual understanding","Critical evaluation","Ethics and privacy"],evidence:["Calculated assessment score"],actions:["Practise source verification","Review where AI should not be used"],caution:"AI literacy describes current readiness, not personal worth."},
    "ai-readiness":{id:"ai-readiness",title:"AI Readiness",interpretation:`Current level: ${assessmentResults?.summary?.ai_readiness_level||"Emerging"}.`,signals:["Practical tool use","Workflow integration","Willingness to learn"],evidence:["Calculated assessment score"],actions:["Test one AI-assisted workflow","Document verification steps"],caution:"Readiness can change through practice and support."},
    "change-readiness":{id:"change-readiness",title:"Change Readiness",interpretation:assessmentResults?.summary?.change_readiness||"Exploring options",signals:["Motivation","Time","Constraints"],evidence:["Calculated professional-transition indicators"],actions:["Choose a reversible experiment","Identify the strongest constraint"],caution:"This is non-clinical transition feasibility, not a resilience diagnosis."},
    ...Object.fromEntries(careerMatches.map(x=>[`career-${x.id}`,{id:`career-${x.id}`,title:x.title,interpretation:x.explanation,confidence:x.alignment_score/100,signals:x.supporting_factors,evidence:x.transferable_skills.map(item=>String(item.original_skill||"Transferable skill")),actions:[x.next_step,"Compare with up to two other directions"],caution:"A career match is decision support, not a directive or guarantee."}]))
  }),[assessmentResults,careerMatches,details]);
  if(error)return <div className="organic-section text-red-600">{error}</div>; if(!profile)return <div className="organic-section theme-muted">Loading your explainable Human Potential Profile...</div>;
  const displayedArchetype=feedback.archetype_override||profile.primary_archetype.name; const alignment=average(profile.values.map(x=>x.score)); const contribution=average(profile.contribution_domains.map(x=>x.score));
  return <div className="organic-page"><header className="text-center"><h1 className="font-display text-4xl font-semibold theme-text sm:text-5xl">Your Human Potential Map</h1><p className="mt-3 text-lg theme-muted">Your answers suggest an exploratory profile you can confirm, correct, or expand.</p>{status&&<p className="mt-3 text-sm text-[color:var(--teal)]" role="status">{status}</p>}</header><div className="grid gap-6 xl:grid-cols-[20rem_1fr_20rem]">
    <aside className="space-y-4"><section className="glass-card p-5"><p className="text-sm font-bold theme-text">Your Archetype</p><div className="mt-4 flex gap-3"><span className="organic-icon-orb h-12 w-12"><UserRound size={22}/></span><div><h2 className="font-display text-2xl font-semibold text-[color:var(--teal)]">{displayedArchetype}</h2><p className="text-xs theme-muted">{Math.round(profile.primary_archetype.confidence*100)}% answer coverage</p></div></div><p className="mt-3 text-sm leading-6 theme-muted">{profile.primary_archetype.summary}</p><label className="mt-4 block text-xs font-semibold theme-text">Adjust display name<select value={feedback.archetype_override||""} onChange={e=>void saveFeedback({...feedback,archetype_override:e.target.value||null})} className="organic-input mt-2"><option value="">Use generated suggestion</option>{[profile.primary_archetype.name,profile.secondary_archetype.name,"Visionary Architect","Human-Centred Integrator","Curious Explorer"].filter((v,i,a)=>a.indexOf(v)===i).map(x=><option key={x}>{x}</option>)}</select></label></section>
    <section className="glass-card p-5"><h2 className="font-display text-lg font-bold theme-text">Top Strengths</h2><div className="mt-4 space-y-4">{profile.strengths.map(item=>{const score=feedback.strength_adjustments[item.name]??item.score;return <div key={item.name} title={item.explanation}><div className="flex justify-between text-sm"><b className="theme-text">{item.name}</b><span className="theme-muted">{score}</span></div><input aria-label={`Importance of ${item.name}`} type="range" min="0" max="100" value={score} onChange={e=>setFeedback({...feedback,strength_adjustments:{...feedback.strength_adjustments,[item.name]:Number(e.target.value)}})} onMouseUp={()=>void saveFeedback(feedback)} className="mt-2 w-full organic-range-action"/><p className="mt-1 text-xs theme-muted">{item.explanation}</p></div>})}</div></section>
    <section className="glass-card p-5"><h2 className="font-display text-lg font-bold theme-text">AI Collaboration Style</h2><p className="mt-3 font-bold text-[color:var(--teal)]">{profile.ai_collaboration_style.name}</p><p className="mt-2 text-sm theme-muted">{profile.ai_collaboration_style.summary}</p><Link to={`/report/${profile.id}`} className="organic-button-secondary mt-4 w-full">View Full AI Profile <ArrowRight size={16}/></Link></section></aside>
    <section className="space-y-5"><div className="glass-card p-4"><div className="flex flex-wrap items-center gap-2"><span className="organic-chip"><Layers3 size={16}/> Map layer</span>{[["human-potential","Human Potential"],["personality","Personality & Work Style"],["career-interests","Career Interests"],["work-values","Work Values"],["skills-evidence","Skills Evidence"],["ai-readiness","AI Readiness"],["career-compatibility","Career Compatibility"]].map(([value,label])=><button key={value} type="button" onClick={()=>setMapLayer(value)} className={mapLayer===value?"organic-action-selected rounded-full px-4 py-2 text-sm font-bold":"organic-chip"}>{label}</button>)}</div>{mapLayer==="career-compatibility"?<Link to={`/workspace/${profile.id}/career-compatibility`} className="organic-button-secondary mt-4"><BriefcaseBusiness size={16}/> Open Career Compatibility Map</Link>:null}</div><Suspense fallback={<div className="glass-card min-h-[42rem] p-5">Loading 3D map...</div>}><HumanPotentialGlobe nodes={nodes} selectedId={selectedId} onSelect={setSelectedId} centerTitle={mapLayer==="human-potential"?displayedArchetype:"Career Assessment Layer"} centerSubtitle={alignment!=null?`Alignment indicator ${alignment}`:"Alignment emerging"} className="min-h-[42rem]"/></Suspense><PotentialNodeDetailPanel node={enrichedDetails[selectedId]} feedback={feedback} onSave={saveFeedback}/></section>
    <aside className="space-y-4"><section className="glass-card p-5"><h2 className="font-display text-lg font-bold theme-text">Contribution Domains</h2><div className="mt-4 space-y-3">{profile.contribution_domains.map(item=><div key={item.name}><div className="flex justify-between text-sm"><b className="theme-text">{item.name}</b><span className="theme-muted">{item.score}</span></div><p className="mt-1 text-xs theme-muted">{item.explanation}</p></div>)}</div></section><section className="glass-card p-5"><h2 className="font-display text-lg font-bold theme-text">Recommended Learning Paths</h2><div className="mt-4 space-y-3">{profile.recommended_learning_paths.filter(x=>!feedback.hidden_recommendations.includes(x.name)).map(item=><article key={item.name} className="rounded-xl border border-[color:var(--border-soft)] p-3"><Link to="/learning-paths" className="font-bold text-[color:var(--teal)]">{item.name}</Link><p className="mt-1 text-xs theme-muted">{item.level} · {item.duration}</p><p className="mt-1 text-xs theme-muted">{item.reason}</p><button type="button" onClick={()=>void saveFeedback({...feedback,hidden_recommendations:[...feedback.hidden_recommendations,item.name]})} className="mt-2 text-xs theme-muted underline">Hide recommendation</button></article>)}</div></section><section className="glass-card p-5"><p className="font-display text-lg italic theme-text">“{profile.ethical_note}”</p></section><section className="glass-card p-5"><h2 className="font-display text-lg font-bold theme-text">Actions</h2><div className="mt-3 space-y-2"><button type="button" onClick={()=>void share()} className="organic-chip w-full justify-start"><Share2 size={16}/> Share My Map</button><button type="button" onClick={()=>navigate(`/report/${profile.id}`)} className="organic-chip w-full justify-start"><Download size={16}/> Download My Map</button><button type="button" onClick={()=>window.confirm("Retake the diagnostic? Your existing profile remains saved.")&&navigate("/diagnostic")} className="organic-chip w-full justify-start"><RefreshCw size={16}/> Retake Assessment</button><Link to={`/roadmap/${profile.id}`} className="organic-button w-full">Explore My Roadmap <Sparkles size={16}/></Link></div></section></aside></div>
    <section className="glass-card grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4" title="These are exploratory OrganicAI Compass indicators, not clinical or psychometric measurements.">{[["Profile Alignment",alignment!=null?`${alignment}/100`:"Not enough data yet"],["Growth Momentum","Not enough data yet"],["Collaboration Readiness",profile.ai_collaboration_style.recommended_uses.length?"Signals available":"Not enough data yet"],["Contribution Potential",contribution!=null?`${contribution}/100`:"Not enough data yet"]].map(([label,value])=><div key={label} className="rounded-2xl border border-[color:var(--border-soft)] p-4"><p className="text-xs theme-muted">{label}</p><p className="mt-2 font-display text-xl font-semibold theme-text">{value}</p></div>)}</section></div>;
}
